### ISSUE TITLE
usage example?

### ISSUE THREAD

**Issue by trentgrover-wf** [frankwallis/plugin-typescript#1]
Can you provide a simple usage example?  When using this similarly to other SystemJS plugins, I only get an error.

**Comment by trentgrover-wf** [comment]
![screen shot 2015-01-30 at 4 17 50 pm](https://cloud.githubusercontent.com/assets/3778206/5984412/a208470c-a89b-11e4-95c4-90a8270e5946.png)

**Comment by frankwallis** [comment]
I have published a new version which should be working, although there are a few outstanding issues. For usage please see the example project contained within, or I also have a larger test application which I am working on [here](https://github.com/frankwallis/tower/tree/systemjs)

**Comment by frankwallis** [comment]
This should be usable now if you want to give it another try
