### ISSUE TITLE
Load the correct lib.d.ts file depending on the target.

### ISSUE THREAD

**Issue by peterjuras** [frankwallis/plugin-typescript#101]
Currently only the lib.es6.d.ts file is loaded by default, regardless of the chosen target. The default behavior of the typescript compiler is to load the lib.d.ts file if the target is ES5 and lib.es6.d.ts if the target is ES6.

The current behavior breaks some typings, including es6-promise, since it throws Duplicate Identifier errors during compilation.

See [compiler-host.ts | Line 74](https://github.com/frankwallis/plugin-typescript/blob/master/src/compiler-host.ts) and [factory.ts | Line 101](https://github.com/frankwallis/plugin-typescript/blob/233d38944d4cea89079003225b2481c2126275f9/src/factory.ts)

**Comment by frankwallis** [comment]
This is actually deliberate but it stems from when there was always an ES6 environment provided by the built-in traceur/babel transpilers. TypeScript is also a bit inflexible here as you cannot include lib.es6.d.ts when compiling to es5 which you might want to do if you are polyfilling es6.

I am reluctant to change the default behaviour, but I am open to adding another option ```libTarget``` which you could use? Alternatively I have achieved similar by specifying ```noLib: true``` and referencing ```./node_modules/typescript/lib/lib.d.ts``` in the ```files``` array in tsconfig.json?

**Comment by peterjuras** [comment]
Thanks for the quick response!

I see where you are coming from, I think an option like libTarget might help to allow compilation in a lot of contexts and would solve my problem. 

I don't have a node_modules that is being served in my setup and referencing the lib.d.ts from within jspm_packages for example is prone to error because of the strict typings.

**Comment by frankwallis** [comment]
I've added a ```targetLib``` option in 2.5.11, set it to "es5" to type-check against lib.d.ts.

**Comment by peterjuras** [comment]
Thanks a lot, it works great!
