### ISSUE TITLE
Latest update (3.0.0) breaks transpilation during bundling

### ISSUE THREAD

**Issue by frederikschubert** [frankwallis/plugin-typescript#103]
I am using plugin-typescript 3.0.0 and jspm 0.16.27. Now when I run my application in the browser everything works just fine. However when I bundle my application using `jspm bundle-sfx` the code is not transpiled to es5. I am using this command to bundle my application:
```bash
jspm bundle-sfx src/app.ts bundle.js
```
Here is a part of my config.js:
```javascript
  transpiler: "ts",
  typescriptOptions: {
    "module": "system",
    "noImplicitAny": false,
    "typeCheck": false,
    "tsconfig": true
  },
  packages: {
    "src": {
      "defaultExtension": "ts"
    }
  },
...
```
And my tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es5",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "system",
    "outDir": "tmp",
    "sourceMap": true,
    "moduleResolution": "node",
    "baseUrl": "./jspm_packages"
    ...
```

**Comment by frankwallis** [comment]
Thanks, this is due ti a change added for rollup support. See https://github.com/frankwallis/plugin-typescript/issues/97#issuecomment-181517473

I am going to revert it for the time being.

**Comment by frankwallis** [comment]
I've reverted it in 3.0.2.

**Comment by frederikschubert** [comment]
Thanks for the quick fix! Keep up the great work.
