### ISSUE TITLE
Dependency on dev version of TypeScript

### ISSUE THREAD

**Issue by nillis** [frankwallis/plugin-typescript#104]
Currently the plugin depends on the nightly build of TypeScript. How do you see this evolve? 
When 1.9 releases, depending on this version? Isn't it better to lock the dev version till the 1.9 release to prevent bugs in the nightly build causing the plugin to break?

**Comment by frankwallis** [comment]
I am planning to pin to 1.8.2 when it is released (hopefully next week).

**Comment by frankwallis** [comment]
I've updated to use typescript@1.8.2
