### ISSUE TITLE
What are the !transpiled files and how do they differ from the .js files?

### ISSUE THREAD

**Issue by Vaccano** [frankwallis/plugin-typescript#105]
If I have a file called something.ts, sometimes the chrome debugger shows something.ts!transpiled and sometimes it shows something.js.

I assume the something.ts!transpiled is what this plugin is doing for me.  Is that right?  

Does that mean when I have a something.js, that something is going wrong?

**Comment by frankwallis** [comment]
Yes I would expect it to show something.ts & something.ts!transpiled. I don't know why you are seeing something.js.

**Comment by frankwallis** [comment]
Hopefully you resolved this, otherwise if you can post a repro I will investigate.

**Comment by Vaccano** [comment]
I did not resolve it.  But I don't know why it does it.  If I can repro it I will post it.
