### ISSUE TITLE
TypeScript/ES2015 bundle fails due to unreplaced TypeScript syntax

### ISSUE THREAD

**Issue by nlwillia** [frankwallis/plugin-typescript#106]
I'm trying to use TypeScript and ES2015 features and have them work in browser or bundled.  I learned the hard way that TypeScript does not attempt to transpile ES2015 iterator features.  It will pass for/of syntax right through to the browser, but if what's being iterated is not an array, it won't work.  The solution as I understand it is to configure TypeScript with `target: "es6"` and then run the result through a more complete transpiler like babel.  This is working well enough in the browser, but when I try to bundle, I get an error because the file also contains TypeScript syntax which doesn't appear to have been replaced.  (The error below is on the colon in the type definition.)

JSPM is at 0.16.29.  I ran `jspm install ts` and `jspm dl-loader babel`.

```javascript
// package.json
{
  "jspm": {
    "dependencies": {
      "plugin-typescript": "github:frankwallis/plugin-typescript@^4.0.1",
      "ts": "github:frankwallis/plugin-typescript@^4.0.1"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4",
      "typescript": "npm:typescript@^1.6.2"
    }
  }
}
```
```javascript
// config.js
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  typescriptOptions: {
    "module": "es2015",
    "target": "es6",
    "sourceMap": false,
	"removeComments":true,
    "inlineSourceMap": true,
    "listFiles": true
  },
  paths: {
    "npm:*": "jspm_packages/npm/*",
    "github:*": "jspm_packages/github/*"
  },

  packages: {
    "src": {
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    }
  },

  map: {
    "babel": "npm:babel-core@5.8.35",
    "babel-runtime": "npm:babel-runtime@5.8.35",
    "core-js": "npm:core-js@1.2.6",
    "ts": "github:frankwallis/plugin-typescript@4.0.1",
    "ts-runtime": "npm:babel-runtime@5.8.35",
    "typescript": "npm:typescript@1.8.2",
    "github:frankwallis/plugin-typescript@4.0.1": {
      "typescript": "npm:typescript@1.8.2"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.35": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
```
```html
<html>
<head>
    <title>Test</title>
    <script src="jspm_packages/system.src.js"></script>
    <script src="config.js"></script>
</head>
<body>
    <script>
        System.import('src/main');
    </script>
</body>
</html>
```
```javascript
// src/main.ts
class Foo {
	[Symbol.iterator]() {
		let m = new Map();
		m.set(1, '1');
		m.set(2, '2');
		m.set(3, '3');
		return m.values();
	}
}

const foo:Foo = new Foo();

for (const x of foo) {
	console.log(x);
}
```
```
$> jspm bundle-sfx src/main
     Building the single-file sfx bundle for src/main...

err  MultipleErrors: Error compiling esm module "src/main.ts" at src\main.ts
        src/main.ts:11:7: const variables must have an initializer
     src/main.ts:11:10: Semi-colon expected
     src/main.ts:11:10: Unexpected token :
     src/main.ts:11:11: Semi-colon expected
```

**Comment by frankwallis** [comment]
I've updated the angular2 example so that it is using the same configuration, and it is not giving me any errors when bundling. Perhaps you could try running that and see if it works for you?

**Comment by nlwillia** [comment]
Thanks for checking.  It looks like this is due to a JSPM bug.  After updating from 0.16.29 to 0.16.30, I don't get the build error anymore.

**Comment by nlwillia** [comment]
Looks like I spoke too soon.  `bundle-sfx` no longer errors, but it's not producing correct output.  It looks like something that came out of the typescript compiler but didn't go through babel because it still contains things like `Symbol.iterator()` and `x of foo`.  In browser (testing in Firefox instead of Chrome since it's currently missing more ES6 features), I can look in `main.ts!transpiled` and see that all of the syntax has been compiled down to ES5, but build.js is not fully reduced.

This is with 0.16.31.  The beta appears to handle this example correctly, but I've had other issues with building under the beta, so I've not been able to move over yet.

**Comment by frankwallis** [comment]
This looks like an issue in systemjs-builder related to the new rollup support. I have reproduced it here: https://github.com/frankwallis/jspm-ts-bundle (in master).

Internally, when ```load.originalSource``` gets set then the bundled output is not transpiled to es5 for some reason. If you can disable the rollup support then that may fix it, otherwise try using an older version of systemjs-builder or report this issue on that repo.

**Comment by nlwillia** [comment]
Thanks for the analysis.  I'm back to not being able to reproduce it (on a different system today) which is really strange.  That at least gives me some place to look if it recurs.  I'll follow up if I can find anything more specific about what's going on.

**Comment by nlwillia** [comment]
Sorry...Monday brain.  I forgot which build error this was (hitting way too many of these lately).  It is still occurring.  It's likely not an issue with this plugin though so I'll leave this closed.
