### ISSUE TITLE
use different versions of TS SDK

### ISSUE THREAD

**Issue by rolandjitsu** [frankwallis/plugin-typescript#111]
Is it possible to use a different version of TS? It would be nice if I could use the `next` branch to get the latest features and bug fixes.

**Comment by frankwallis** [comment]
Yes it is, you just need to add an override, see [here](https://github.com/frankwallis/plugin-typescript#override-typescript-version) for an example.

**Comment by rolandjitsu** [comment]
@frankwallis thanks. I must have overlooked that section.

**Comment by rolandjitsu** [comment]
@frankwallis actually it failed when I tried to `jspm install ts=github:frankwallis/plugin-typescript@^4.0.2 -o "{dependencies: {typescript: 'npm:typescript@next'}}"`. It gave me a `err  Installing github:frankwallis/plugin-typescript@4.0.2, no version match for npm:typescript@next`. Do you know what is that about?

**Comment by frankwallis** [comment]
I think ```@next``` only works for npm, for jspm you have to specify the actual version number e.g. ```typescript@1.9.0-dev.20160317```

**Comment by rolandjitsu** [comment]
@frankwallis ok, makes sense. Thanks
