### ISSUE TITLE
How to improve Transpiling speeds with jspm and TS module...

### ISSUE THREAD

**Issue by born2net** [frankwallis/plugin-typescript#112]
In an effort to understand better how JSPM / TS plugin works, as I am trying to improve my development re-launch cycles speeds which right now take about 5-8 seconds each time I reload the browser.

So I am using Angular 2 with Typescript, and I am trying to improve the transpiling time of TS in the browser (although to be honest, when looking at the load times via network tab in google dev tool, I do see a lot of the time is being spent just fetching files via JSPM... but I guess nothing we can do about that).

So my question is, if I convert my project into many smaller npm type libs, which are developed in TS but when provided through the npm already come with the transpiled JS equivalents, will this improve load times as the TS module will not need to re-transpile them? or will that not be the case?

any other tips?

regards

Sean.

**Comment by frankwallis** [comment]
Yes I think the biggest performance gain would be had by configuring angular2 to be loaded as a systemjs bundle. Currently each time you reload the browser the whole of angular2 is transpiled which is very slow as there are a large number of files. angular2 distributes pre-transpiled bundles under the ```bundles``` directory and it should be possible to configure systemjs to load these files instead. I did try to get this working a while back but ran into issues with the alpha release.

There is more information about bundle configuration [here](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#bundle). If I find some time I will try to set this up in the example project. It may also be possible to get this working by including the angular2 bundle with a script tag. If you do get this working I would be very interested to hear about it!

**Comment by born2net** [comment]
tx for the update, I will check it out, I am also going to investigate the new hot-loader from jspm: http://jspm.io/0.17-beta-guide/hot-reloading.html
could be a game changer for ng2 development...
tx

Sean
