### ISSUE TITLE
TypeCheck strict doesn't work for me 

### ISSUE THREAD

**Issue by jtamary** [frankwallis/plugin-typescript#114]
When I change typeCheck to "strict" from true, the typecheck shows the errors but doesn't fail the bundling.

I've tried to use the example\angular with the same result:
> TypeScript plugin-typescript-master/examples/angular/src/example-controller.ts:13:15
> TypeScript Cannot find name 'string2'. (TS2304)
> Build complete, go to http://127.0.0.1:8080/index-bundle.html

I'm using:
Jspm@0.17-beta-11
plugin-typescript@4.0.2

Thanks,
Jonathan

**Comment by frankwallis** [comment]
thanks for raising this, it should be fixed in 4.0.5.

**Comment by jtamary** [comment]
thanks :)
