### ISSUE TITLE
README request

### ISSUE THREAD

**Issue by kylecordes** [frankwallis/plugin-typescript#115]
This would probably be obvious if I studied it for a while, but it is not at first glance and I suspect that applies to others also:

I request that the readme file contain a section explaining how this is different from (and presumably much better than) the typescript support already in SystemJS. What kinds of problems might I have, that might lead me to pick this up instead of the built-in support?

**Comment by frankwallis** [comment]
Thanks for raising this, I've add a paragraph under 'Overview' which hopefully clarifies things a bit more, please let me know if you think I should add anything else.

**Comment by kylecordes** [comment]
Thank you, that is very helpful!
