### ISSUE TITLE
Re-Export not working

### ISSUE THREAD

**Issue by frederikschubert** [frankwallis/plugin-typescript#118]
I am using version 4.0.6 of the plugin and 0.16.33 of jspm.

When I try to use modules that are re-exported via `export * from "./module1"` they are undefined. When I directly import them they are defined. I don't know whether this is an issue with systemjs or this plugin.

# Update
I tried it with the angular2 example project and it worked so the error is on my side. Will close this issue but update it, once I found the error for future reference.

**Comment by frederikschubert** [comment]
Ok this error is really weird. Apparently re-exporting an Angular 2 Component class works, whereas a Service does not. I can reproduce that with the example.
```diff
diff --git a/examples/angular2/src/calculator-component.ts b/examples/angular2/src/calculator-component.ts
index 9298b4e..9aa3037 100644
--- a/examples/angular2/src/calculator-component.ts
+++ b/examples/angular2/src/calculator-component.ts
@@ -1,5 +1,5 @@
 import {Component} from 'angular2/core';
-import {CalculatorStore, CalculatorState} from "./calculator-store";
+import {CalculatorStore, CalculatorState} from "./facade";
 import calculatorTemplate from "./calculator-view.html";
 
 @Component({
diff --git a/examples/angular2/src/facade.ts b/examples/angular2/src/facade.ts
new file mode 100644
index 0000000..806f950
--- /dev/null
+++ b/examples/angular2/src/facade.ts
@@ -0,0 +1,2 @@
+export * from "./calculator-component";
+export * from "./calculator-store";
\ No newline at end of file
diff --git a/examples/angular2/src/index.ts b/examples/angular2/src/index.ts
index 62d58b3..edfc323 100644
--- a/examples/angular2/src/index.ts
+++ b/examples/angular2/src/index.ts
@@ -1,7 +1,7 @@
 import "../shims.js";
 import {bootstrap} from 'angular2/platform/browser';
 import {Component} from 'angular2/core';
-import {CalculatorComponent} from './calculator-component';
+import {CalculatorComponent} from './facade';
 import "./index.css";
 
 @Component({
```
Toggling the second change breaks the DI, because the CalculatorStore is undefined.

**Comment by frankwallis** [comment]
I believe this is a circular references issue - if you swap the order of the exports in ```facade.ts```, so that ```calculator-store.ts``` is exported first, then it starts working?

This may be due to the fact that the project is compiled to commonjs first and then to system.register format. CommonJS does not handle circular references, but system.register does.

**Comment by frederikschubert** [comment]
Yes you are right with the circular reference! But in my project that has the same error, I transpile directly to system. I don't know if this is a known limitation or a bug. My config:
```javascript
...
  transpiler: "ts",
  typescriptOptions: {
    "module": "system",
    "noImplicitAny": false,
    "typeCheck": false,
    "tsconfig": false,
    "target": "es5",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  packages: {
    "src": {
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        },
        "*.scss": {
          "loader": "scss"
        },
        "*.html": {
          "loader": "text"
        }
      }
    }
  },
...
```
For future reference: When re-exporting a module it is important to re-export the modules in such an order that the dependent module is exported **after** the module it depends on.
