### ISSUE TITLE
Modules are imported twice since 4.0.6 when using typeCheck

### ISSUE THREAD

**Issue by RobinBuschmann** [frankwallis/plugin-typescript#119]
I've created a repo which reproduces the issue:

https://github.com/RobinBuschmann/jspm-plugin-ts-bug.git

- (`npm install`)
- use `npm start` 
- check the browsers console
- the string "This shows up twice in console" is logged twice

These changes from plugin.js causes the issue: https://github.com/frankwallis/plugin-typescript/commit/58cc11c5d0cebf91ba8d00e881fbde1e1b4c948a

**Comment by frankwallis** [comment]
Thank you for raising this, I have pushed a patch in 4.0.7. I probably need to investigate a bit further because it seems that systemjs is treating ```file.ts``` and ```file.ts!ts``` as different modules, but hopefully this will fix the issue for now.
