### ISSUE TITLE
Support / tip button

### ISSUE THREAD

**Issue by guybedford** [frankwallis/plugin-typescript#121]
Hey, was just wondering if you've thought about adding some sort of tip button here?

jspm and SystemJS are starting to get some reasonable tips these days, and it might be worth considering adding something here for all the work you've been doing.

**Comment by frankwallis** [comment]
Interesting idea, I hadn't really thought about it but I will look into it, thanks!

**Comment by frankwallis** [comment]
I've added a tip button, we'll see how it goes...

**Comment by guybedford** [comment]
Awesome, I've passed on fraction of the jspm support!

**Comment by frankwallis** [comment]
wow thanks very much!
