### ISSUE TITLE
Avoid file references being written to bundles

### ISSUE THREAD

**Issue by svi3c** [frankwallis/plugin-typescript#127]
As pointed out in [this issue comment](https://github.com/frankwallis/plugin-typescript/issues/102#issuecomment-219273789) there are some file references written to the bundles.

This behavior leads to problems using hot module replacement when used together with bundling.

**Comment by frankwallis** [comment]
I'm hoping this will automatically be resolved when rollup support becomes available with TypeScript 2.0.
See https://github.com/frankwallis/plugin-typescript/issues/97

**Comment by laurentgoudet** [comment]
Unfortunately this is still an issue when the loader is used in production, as rollup only works for static builds. For now disabling `typeChecks` works around the issue, but it means that the TypeScript build as to be enforced by another way, e.g. a duplicate compilation pass.

**Comment by frankwallis** [comment]
type-checking is no longer supported in 7.0.0 and so I believe this will no longer be an issue
