### ISSUE TITLE
Reference path fails on names with dots?

### ISSUE THREAD

**Issue by mindeavor** [frankwallis/plugin-typescript#13]
I'm trying to use `path="mithril.js/mithril.d.js` in my typescript reference, but `plugin-typescript` is not translating it. Instead I get the following error:

    Not Found: http://127.0.0.1:8080/mithril.js/mithril.d.ts (WARNING: non-Error used)

Here's how to reproduce:

```bash
$ jspm init # `yes` to all defaults
$ jspm install ts
$ echo '/// <reference path="mithril.js/mithril.d.ts" />' > test.js
$ echo '<script src="jspm_packages/system.js"></script><script src="config.js"></script><script>System.import("test.ts!");</script>' > index.html
$ npm install -g live-server
$ live-server
```

**Comment by mindeavor** [comment]
Turns out this might be a jspm issue https://github.com/jspm/jspm-cli/issues/638

**Comment by frankwallis** [comment]
it looks like this is resolved.
