### ISSUE TITLE
examples/angular2 build Does Not Work

### ISSUE THREAD

**Issue by mcwillso** [frankwallis/plugin-typescript#132]
Following the [build instructions](https://github.com/frankwallis/plugin-typescript#examples) for the angular2 example fails with browser errors:
```npm run build``` -  Uncaught reflect-metadata shim is required when using class decorators
```jspm bundle src build/build.js``` - Uncaught ReferenceError: System is not defined

Do I need to ```jspm install``` something else, [i.e.](https://gist.github.com/robwormald/429e01c6d802767441ec)

**Comment by frankwallis** [comment]
I'm not able to recreate this, the ```reflect-metadata``` shim should be loaded in the ```shims.js``` file. Can you confirm the jspm version with ```jspm -v``` and whether you are on windows/mac/linux?
