### ISSUE TITLE
typeCheck strict behavior

### ISSUE THREAD

**Issue by lastmjs** [frankwallis/plugin-typescript#139]
Just a clarification, and if I'm thinking of things incorrectly then there is no issue, but maybe a feature request if possible. With `typeCheck: 'strict'`, I was thinking that if transpiling in the browser, the build would fail and the code would not even run. Is that what is supposed to happen? Because it isn't working for me.

I'm using:
* plugin-typescript v4.0.17

**Comment by frankwallis** [comment]
```typeCheck: strict``` only works when bundling I'm afraid, in the browser the plugin does not get notified by SystemJS when loading is complete so it can't force compile everything.

This is a slightly hacky workaround I have used:

```
   System.import('main.ts')
      then(function() {
         return System.import('plugin-typescript');
      })
      .then(function(pluginTypescript) {
         return pluginTypescript.bundle();
      });
```
