### ISSUE TITLE
Exclude files to be type checked when transpiling in the browser

### ISSUE THREAD

**Issue by lastmjs** [frankwallis/plugin-typescript#142]
The `exclude` property does not seem to be working when I provide a `tsconfig.json` file for transpiling in the browser. I can't seem to find information on how to exclude certain files from being type-checked in the browser.

**Comment by aluanhaddad** [comment]
Exclude isn't for excluding files from type checking it's for excluding them from compilation.

**Comment by lastmjs** [comment]
I see...is there a way to exclude files from being type-checked?

**Comment by aluanhaddad** [comment]
I don't believe so but #96 is very relevant here as it would allow for this as well as other functionality.

**Comment by frankwallis** [comment]
This is not currently possible, but yes #96 would enable you to turn on/off type-checking for specific packages. If you are interested in this feature then please add a comment to that thread outlining your use-case, thanks.
