### ISSUE TITLE
Enumerations not converted to numbers

### ISSUE THREAD

**Issue by edgarhsanchez** [frankwallis/plugin-typescript#143]
With the same typescript .config file I build the project directly with the typescript compiler and then again with this jspm plugin and I get different behavior for enumerations.  Perhaps something isn't passing through to the typescript compiler when this plugin is in the middle?

**Comment by frankwallis** [comment]
This is because the plugin uses 'single-file' mode when transpiling the files, so it is not possible to convert enums to their values as the values are not avbailable at transpile time. See [here](https://github.com/Microsoft/TypeScript/issues/5243) for more info.
