### ISSUE TITLE
 Compilation errors due to not adding /// references

### ISSUE THREAD

**Issue by mrcasado** [frankwallis/plugin-typescript#146]
If I don't add triple slash references I get lots of compilation errors complaining that the type i'm trying to use does not exist. Please correct me if I'm wrong but  I thought that /// references were not needed to be specified in every singe file as long as you use tsconfig.json?. Is there a way for the type checker to work out where the definition file is without adding "///"?

**Comment by frankwallis** [comment]
You need to have ```tsconfig: true``` set in ```typescriptOptions``` and then plugin-typescript will automatically load any declaration files found in the ```files``` array in tsconfig.json. See [here](https://github.com/frankwallis/plugin-typescript/blob/master/examples/angular/tsconfig.json#L8) for example.
