### ISSUE TITLE
Getting 404: Plugin-Typescript@1.0.0

### ISSUE THREAD

**Issue by jennyraj** [frankwallis/plugin-typescript#15]
http://127.0.0.1:8080/jspm_packages/github/frankwallis/plugin-typescript@1.0.0.js Failed to load resource: the server responded with a status of 404 

Hello, I am getting the error as above when running the example task. I installed the npm/jspm etc as instructed. I did a global search and replaced the reference to 1.0.1 (the latest  version) but still getting errors. 

sorry, I am a newbie! Can you help?

Thanks in advance.

**Comment by frankwallis** [comment]
I have updated the readme as there was a missing step - you need to run ```jspm install --dev``` as well as ```jspm install``` inside the 'example' folder. Can you try that and see if it works?

**Comment by jennyraj** [comment]
Thank you so very much for the quick response. Yes, it fixed the issue :) Thanks again!
