### ISSUE TITLE
Do not hardcode noLib=true.

### ISSUE THREAD

**Issue by aindlq** [frankwallis/plugin-typescript#150]
Currently typescript option `noLib=true` is hard-coded, which is unfortunate because in typescript 2.0 there is new `lib` option which gives the ability to specify set of libs to use:

```
            "lib": {
              "description": "Specify library file to be included in the compilation. Requires TypeScript version 2.0 or later.",
              "type": "array",
              "items": {
                "type": "string",
                "enum": [ "es5", "es6", "es2015", "es7", "es2016", "es2017", "dom", "webworker", "scripthost", "es2015.core", "es2015.collection", "es2015.generator", "es2015.iterable",
                        "es2015.promise", "es2015.proxy", "es2015.reflect", "es2015.symbol", "es2015.symbol.wellknown", "es2016.array.include", "es2017.object", "es2017.sharedmemory" ]
              }
            },

```
But it is not possible to use `lib` with `noLib=true`. Would be great to have this option supported by the plugin.

**Comment by skorlir** [comment]
Just ran into this as well. It is definitely desirable to be able to use the "lib" option with "jspm bundle" commands, in particular - otherwise we get compiler errors when using ES6 that is well-supported in the browser, such as Promise!
