### ISSUE TITLE
Looking under wrong directory for index.d.ts

### ISSUE THREAD

**Issue by bmayen** [frankwallis/plugin-typescript#154]
I just updated to Angular 2 rc6. Each package.json file points 'main' to a umd bundle under a 'bundles' folder but the 'index.d.ts' file is located under each package root. Previously I had config for all of these packages set like:

```
let ngPkgNames = [
    '@angular/common',
    '@angular/compiler',
    '@angular/core', 
    ...
];
ngPkgNames.forEach(function(pkgName) {
    packages[pkgName] = {
      meta: {
        '*.js': {
          typings: true
        }
      }
    };
  });
```

This no longer works as it looks for a .d.ts file with the same name as the umd bundle. I assume I instead need to tell it to pull typings from 'index.d.ts', correct? If I change this to `typings: 'index.d.ts'`, I get the following error: "Error on fetch for @angular/index.d.ts!github:frankwallis/plugin-typescript@5.0.19/plugin.js". It's looking under the parent '@angular' folder instead of the package folders' roots.

Side note: This may have come up before, but is it not possible to read the typings path from the package.json files and avoid this config entirely?

**Comment by bmayen** [comment]
The cause is this line in resolver.js: `var packageName = importName.split('/')[0];`

What is the intent of this vs using `importName` as is?

**Comment by bmayen** [comment]
How about something like:
```
var pkgSegments = importName.split('/');
var packageName = pkgSegments[0];

if (packageName.indexOf('@') === 0) {
    packageName += '/' + pkgSegments[1];
}
```

**Comment by bmayen** [comment]
Tested the release for this. Looks good! 🎉

**Comment by frankwallis** [comment]
Thanks - getting typings information from package.json isn't going to happen for reasons discussed in #102 (and sometimes it is not there anyway). However in 5.1.1 I have added a new compiler option ```typings``` which you can use instead of systemjs metadata. I hope that this will make it much easier to configure external typings and I also think it aligns better with the new ```types``` compiler option.

**Comment by aluanhaddad** [comment]
@frankwallis That is fantastic. If only the TypeScript compiler would implement this behavior.
