### ISSUE TITLE
update typescript dep to recent @next release for ES3/5 transpilation of async/await/generators

### ISSUE THREAD

**Issue by piotrwitek** [frankwallis/plugin-typescript#156]
TypeScript async/await/generators transpilation to ES3/5 is finally in the master repo and will be provided in recent @next TypeScript build.
Wanted to ask if you consider updating typescript dependency to the recent @next version or you'll rather wait for more stable release?
https://github.com/Microsoft/TypeScript/issues/1564#issuecomment-245148134

I know that this feature is one of the highly anticipated by the community, so I would be happy to know if you plan to add it early, because otherwise I would like to create a fork of your repo and include it myself so I can play with it as soon as possible.

**Comment by bmayen** [comment]
You can override the included typescript version. https://github.com/frankwallis/plugin-typescript#override-typescript-version

**Comment by piotrwitek** [comment]
Thanks, that's good solution for my case, closing
