### ISSUE TITLE
Feature request: bundle

### ISSUE THREAD

**Issue by kylecordes** [frankwallis/plugin-typescript#159]
Currently this plug-in ships in the form of a few handfuls of files, bundled as systemjs modules. It would be helpful if a single bundle were also provided.

The idea here is to enable development workflows, demos, plunkers, etc. with a modest number of roundtrips to grab the needed tooling. Such a bundle would mean just one round-trip for plugin-typescript, and one for typescript itself (which already ships a bundle that System can consume).

Although the context I have in mind is for Angular 2 applications, I believe it is equally applicable to other uses of this plug-in.

**Comment by frankwallis** [comment]
Thanks for raising this, I have actually wanted to do this for a while but was blocked by https://github.com/Microsoft/TypeScript/issues/6319 which is now resolved. I have just released 5.2.0 which distributes the plugin as a single file bundled with rollup.

**Comment by kylecordes** [comment]
Thank you!
