### ISSUE TITLE
Typescript 2.0 support

### ISSUE THREAD

**Issue by atrauzzi** [frankwallis/plugin-typescript#160]
Any idea if things will work with the latest release?

https://blogs.msdn.microsoft.com/typescript/2016/09/22/announcing-typescript-2-0/

**Comment by aluanhaddad** [comment]
@atrauzzi I'm would imagine it will. I have been using plugin-typescript 5.1.2 with nightly builds for several months. It has worked with 1.9.x-dev and 2.1.x-dev releases. There was an issue in 2.1.x where where I had to run 
```powershell
jspm install npm:source-map-support
```
but otherwise no issues

**Comment by frankwallis** [comment]
The plugin is set to use typescript^2.0.0 (see [here](https://github.com/frankwallis/plugin-typescript/blob/master/package.json#L57)) so by default it should now install with 2.0.3 and that is working fine.
