### ISSUE TITLE
Uncaught (in promise) Error: (SystemJS) exports is not defined

### ISSUE THREAD

**Issue by paarthk** [frankwallis/plugin-typescript#163]
Hello all. I'm running into an issue working with this plugin where I keep getting "exports is not defined". The full error is here:

```
undefined:1 Uncaught (in promise) Error: (SystemJS) exports is not defined
	ReferenceError: exports is not defined
	    at eval (http://localhost:8080/jspm_packages/github/frankwallis/plugin-typescript@5.2.2/plugin.js:4:23)
```

I created a completely clean dummy project to see if I still ran into the issue. I did. 

The dummy project's config.js looks like this:

```
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "ts",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  packages: {
    "app": {
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    },
    "ts": {
      "main": "plugin.js"
    },
    "typescript": {
      "main": "lib/typescript.js",
      "meta": {
        "lib/typescript.js": {
          "exports": "ts"
        }
      }
    }
  },
  map: {
    "ts": "github:frankwallis/plugin-typescript@5.2.2",
    "ts-runtime": "npm:babel-runtime@5.8.38",
    "typescript": "npm:typescript@2.0.3",
    ... (other things JSPM installed).
```

With a simple HTML file:

```
<html>
<body>
<script src="/jspm_packages/system.js"></script>
<script src="/config.js"></script>
<script>
    System.import('app/main');
</script>
</body>
</html>
```

and a similarly simple app/main.ts

```
let message :string = 'hello world';
console.log(message);
```

Finally, the package.json

```
{
  "name": "test",
  "version": "0.0.1",
  "devDependencies": {
    "jspm": "^0.16.46"
  },
  "jspm": {
    "dependencies": {
      "ts": "github:frankwallis/plugin-typescript@^5.2.2",
      "typescript": "npm:typescript@^2.0.3"
    },
    "devDependencies": {
      "ts-runtime": "npm:babel-runtime@^5.8.24"
    }
  }
}

```

Is this perhaps an issue with the project? As far as I can tell I've followed the directions in the README.

**Comment by frankwallis** [comment]
Apologies, I released a bad build in 5.2.2, can you please retry with 5.2.3?

**Comment by paarthk** [comment]
Thanks for the quick turnaround time @frankwallis. Glad I'm not crazy.

I installed the update and am now getting a different error,

```
system.src.js:122 Uncaught (in promise) Error: (SystemJS) require is not defined
	ReferenceError: require is not defined
	    at eval (http://localhost:8080/jspm_packages/npm/typescript@2.0.3/lib/typescript.js:54832:4)
```

I mucked about with typescriptOptions for a few minutes but considering this is the typescript lib file itself, I suspect that doesn't have any effect.

**Comment by frankwallis** [comment]
I think if you are using jspm then you don't need this part of you system.config.js:

```
"ts": {
      "main": "plugin.js"
    },
    "typescript": {
      "main": "lib/typescript.js",
      "meta": {
        "lib/typescript.js": {
          "exports": "ts"
        }
      }
    }
```
Try removing it, deleting ```jspm_packages``` and then re-running ```jspm install```
Can you also confirm what version of jspm you are using?

**Comment by paarthk** [comment]
Fantastic @frankwallis that worked, thank you. Is it mentioned anywhere in the docs that you don't need that if you use jspm? If not, that might be a worthwhile change. 

I hope you won't mind if I close this. Thanks again for resolving it so quickly.

**Comment by frankwallis** [comment]
There are 2 sets of instructions, one for JSPM users and one for SystemJS-only users. I have updated the readme to make this a bit clearer. Thanks for your feedback.
