### ISSUE TITLE
TypeScript is not a dependency

### ISSUE THREAD

**Issue by lastmjs** [frankwallis/plugin-typescript#165]
Did this change? Now when I `npm install` TypeScript is not included. This has been causing multiple issues for me over the last few days.

**Comment by frankwallis** [comment]
Thanks for raising this, it got updated to a development dependency when I needed to use typescript@next to build the project. I have changed it back in 5.2.7.

I would also be very interested to know how you are using the plugin with npm?

**Comment by lastmjs** [comment]
On one team I use the [SystemJS builder](https://github.com/systemjs/builder) to do all of our bundling for development and production. Part of my config uses this plugin to do the transpilation. I use npm for all of our dependencies and our build process.

Another project I'm working on is [es-no-build](https://github.com/lastmjs/es-no-build). It also uses this plugin to do the transpilation in the browser. It makes it really easy to start developing with TypeScript, ES6, async await, and es6 modules, without any kind of build process on the developer's machine.

I usually use that on small projects, and on server-side code so that I can just get up and going quickly.

I really like the idea of using npm for all things dependencies and build process, and I haven't seen the need for JSPM. Once TypeScript 2.1 comes out, I'm planning on experimenting with using it directly to do transpilation. If I set it's module to `system`, and use the es6 module loader polyfill, I should be able to emulate even closer the standard future. I'm trying to stick close to the standards to future-proof my projects.

Anyway, that's a little bit about how I use the plugin.

**Comment by frankwallis** [comment]
That's really interesting, thanks. I completely agree with you about npm, for me it's mainly because it makes testing client-side code in nodejs **much** easier. Also agree the in browser stuff is great for small projects and prototyping. I'm using typescript@next to compile async/await in plugin-typescript now and it seems really solid. Thanks for the info.

**Comment by frankwallis** [comment]
@lastmjs you may also be interested in this project: https://github.com/alexisvincent/systemjs-config-builder , it constructs a systemjs config file from package.json/node_modules
