### ISSUE TITLE
Intercept type check logging

### ISSUE THREAD

**Issue by lastmjs** [frankwallis/plugin-typescript#183]
I would like to somehow intercept the results of type checking so that I can do some things with them before sending them to the user. Is there a good way of doing this that `plugin-typescript` provides? Ideally, since I'm using `plugin-typescript` with `systemjs-builder`, it would be nice if in the output of `compile` the type checking results were presented as a property on the output.

**Comment by frankwallis** [comment]
I think it should be easy enough to add the errors to the systemjs metadata for each file, do you just want the error messages as strings or do you need more structured output, for example to differentiate between warnings and errors?

**Comment by lastmjs** [comment]
Sounds great! I'm not sure what I'll need, but if it isn't too much trouble I think sending over as much information as possible would be best. For my use case I am eventually going to be showing the user the exact error messages that TypeScript would be outputting to the console, if that helps.

**Comment by frankwallis** [comment]
I have added the errors to the file metadata being output, however I am not sure that the type-checking is going to work with the ```builder.compile``` api you are using. The plugin needs all of a file's dependencies (including declaration files) to be passed through before it can fully type-check a file, so the type-errors are not available until sometime after the file has been transpiled.

**Comment by frankwallis** [comment]
The plugin no longer supports type-checking but syntax errors are still provided in file metadata after transpilation
