### ISSUE TITLE
"SystemJS.fetch is not a function" with SystemJS 0.20

### ISSUE THREAD

**Issue by nicolashenry** [frankwallis/plugin-typescript#187]
I got a "SystemJS.fetch is not a function" error using plugin-typescript (6.0.1) with SystemJS 0.20.

I found this if it can help :
https://github.com/systemjs/systemjs/issues/1543

**Comment by nicklasb** [comment]
The error is thrown at plugin.js:431. Basically, this breaks the library, or am I wrong?

**Comment by frankwallis** [comment]
Yes this breaks the library when you have typescriptOptions.tsconfig set. I am working on a fix, will hopefully release tonight but there are other issues with type-checking in 0.20

**Comment by nicklasb** [comment]
FYI: Updated to 6.03, now getting `Error: SystemJS.locate is not a function` instead.

**Comment by frankwallis** [comment]
This will no longer be an issue from 7.0.0 onwards.
