### ISSUE TITLE
Unexpected export encountered on abstract classes

### ISSUE THREAD

**Issue by josh-sachs** [frankwallis/plugin-typescript#197]
```
export abstract class foo {
    public abstract bar(): string;
}
```
Seems to make things choke with "unexpected token export."  I'm still investigating... but there is some issue.

**Comment by josh-sachs** [comment]
Appears to also be an issue with: 

```
export type Foo = {
      bar: string
}
```

**Comment by aluanhaddad** [comment]
This stems from using `"module": "es2015"`, which works perfectly when using the builder for rollup-optimizations, not sure what the status of that feature is but it did use to work. Doesn't have anything to do with abstract class or type declaration.

**Comment by josh-sachs** [comment]
Can close. 

```
{
  target: es5,
  module: 2015
}
```
had been working, and stopped (for me).  I actually managed to get to the bottom of another issue where the plugin wasn't properly loading (systemjs was just loading Typescript without the plugin) and that allowed me to properly flow things from typescript => babel => js which appears to resolve.
