### ISSUE TITLE
tsd.d.ts support

### ISSUE THREAD

**Issue by telekosmos** [frankwallis/plugin-typescript#20]
Hi
Mmmm, I don't know if this is an intended feature or I am doing a wrong workflow, but I came across a situation where the plugin fails to work when the [tsd.d.ts](https://github.com/DefinitelyTyped/tsd#tsddts) is referenced from a Typescript file. 

The point is it fails to load type definition files when they are referred from the single `tsd.d.ts` and managed with [tsd](https://github.com/DefinitelyTyped/tsd). 
Trivial example with jquery working on the `example` directory (after running `jspm install jquery --save`, then `tsd install jquery -s`):
typings/tsd.d.ts
`/// <reference path="jquery/jquery.d.ts" />`

typings/jquery/jqury.d.ts
```javascript
// Type definitions for jQuery 1.10.x / 2.0.x
// rest of definition code 
// ...
```

index.ts
```javascript 
...
/// <reference path="typings/tsd.d.ts" />
...
```

In this case, it tries to load `jspm_packages/github/components/jquery@2.1.4/jquery.d.ts`, which resolves to 404 :-/

As I said, I don't know if this is an intended feature, but I came across the problem and I got a fix by overriding `System.normalize`. 
Let me/us know whether or not the current is the right functionality and I am messing around or, otherwise, if you want a PR or just the function code, which is pretty small.

Regards

**Comment by frankwallis** [comment]
This is an intended feature (see [here](https://github.com/frankwallis/plugin-typescript#declaration-files)), but in my next round of changes I will add a setting to enable/disable this feature as it is non-standard.

**Comment by telekosmos** [comment]
Do you mean the `tsd.d.ts` typings reference file managed by [tsd](http://http://definitelytyped.org/tsd/) is the non-standard one? Don't know that, as it is a sort of side project regarding to the typescript one. I think is convenient but sometimes the definitions managed by `tsd` are a bit poor or outdated...

Anyway, I've worked out a very simple patch to deal with the reference file, you can check it [here](https://github.com/frankwallis/plugin-typescript/compare/master...telekosmos:tsd-support) and I will keep an eye on your next releases.

**Comment by frankwallis** [comment]
In 1.0.5 I have added an option ```resolveAmbientRefs``` which you should set to false in ```typescriptOptions``` and I think this will solve your issue, let me know if there are still problems.

**Comment by telekosmos** [comment]
Tried couple of examples and it seems to work as I expected. 
Well done, good job ;-)

Thanks!!
