### ISSUE TITLE
no such file or directory: `plugin-typescript/lib.js`

### ISSUE THREAD

**Issue by unional** [frankwallis/plugin-typescript#201]
HI @frankwallis ,

Sorry to bother you. This should be a simple mistake on my side but I can't figure out why.

I encountered an issue when using `plugin-typescript` with `systemjs` directly.
My config is like this:

```js
{
  paths: { 'npm:': './node_modules/' },
  baseURL: '/',
  packageConfigPaths: [ 'npm:@*/*/package.json', 'npm:*/package.json' ],
  packages: {
    ts: { main: 'plugin.js' },
    typescript: { main: 'lib/typescript.js',
      "meta": {
        "lib/typescript.js": {
          "exports": "ts"
        }
      } 
    }
  },
  map: {
    ts: './node_modules/plugin-typescript/lib',
    typescript: './node_modules/typescript'
  },
  transpiler: 'ts'
}
```

and when I run it, it errors with `Error: ENOENT: no such file or directory, open '/Users/hwong/github/unional/jsdom-systemjs/node_modules/plugin-typescript/lib.js'`

So seems like `packages/ts/main` is not being recognized.

I'm running it in `jsdom` but It is likely not related.

Here is the repro: https://github.com/unional/jsdom-systemjs/tree/issue
(need to checkout the "issue" branch).

I'm using
- systemjs: 0.20.10
- plugin-typescript: 7.0.6
- jsdom: 9.11.0

Thanks! 🌷 

EDIT: You can reproduce the issue by running `npm i` and then `npm test` or `npm run watch`

**Comment by aluanhaddad** [comment]
@unional probably just a typo in the issue description, but you have

```js
packages: {
    ts: { main: 'plugin.js' },
    typescript: { 
      main: 'lib/typescript.js',
      meta: [Object]
  }
}
```
which doesn't look quite right to me but I may be misunderstanding something. I thought I would mention it just in case :heart:

**Comment by unional** [comment]
Yeah, it is just copied from the console log. meta is

```js
"meta": {
        "lib/typescript.js": {
          "exports": "ts"
    }
}
```

as in the README.

**Comment by aluanhaddad** [comment]
Ah that's what I missed in the repo, I was just looking at the source.

**Comment by unional** [comment]
Thanks for pointing it out. I have updated the OP.

**Comment by frankwallis** [comment]
I'm not sure exactly what the problem is but changing it to

```
ts: {
    packages: {
      'ts': {
        'main': 'lib/plugin.js'
      },
      'typescript': {
        'main': 'lib/typescript.js',
        'meta': {
          'lib/typescript.js': {
            'exports': 'ts'
          }
        }
      }
    },
    map: {
      'ts': './node_modules/plugin-typescript',
      'typescript': './node_modules/typescript'
    },
```

does fix it.

**Comment by unional** [comment]
Thanks.

Yes, that does fix it. In the current working version of that library, I simplify it to this:

```ts
      packages: {
        'typescript': {
          'main': 'lib/typescript.js',
          'meta': {
            'lib/typescript.js': {
              'exports': 'ts'
            }
          }
        },
        'plugin-typescript': {
          'main': 'lib/plugin.js'
        }
      },
      transpiler: 'plugin-typescript'
```

because `plugin-typescript` is the npm package name of this library, so the `map` is no longer needed.

Since the OP is still an issue, you may consider keeping this issue open, or close it and update the README. 🌷

**Comment by frankwallis** [comment]
I'm glad it's sorted, I have updated the readme with the correct configuration, thanks.
