### ISSUE TITLE
Lookup error at node v8.1.2 npm 5.0.3

### ISSUE THREAD

**Issue by Tialcis** [frankwallis/plugin-typescript#207]
npm install

> warn Error on lookup for github:frankwallis/plugin-typescript
>      TypeError: "timeout" must be an unsigned integer
>          at validateTimeout (child_process.js:640:11)
>          at Object.exports.execFile (child_process.js:201:3)
>          at exports.exec (child_process.js:138:18)
>          at module.exports (/Users/siclait/Documents/math-square-master-08fd93a8f129861368f4cf254f7f51a9fa7084b5/node_modules/jspm-github/exec-git.js:64:5)
>          at /Users/siclait/Documents/math-square-master-08fd93a8f129861368f4cf254f7f51a9fa7084b5/node_modules/jspm-github/github.js:382:7
>          at initializePromise (/Users/siclait/Documents/math-square-master-08fd93a8f129861368f4cf254f7f51a9fa7084b5/node_modules/rsvp/dist/rsvp.js:589:5)
>          at new Promise$1 (/Users/siclait/Documents/math-square-master-08fd93a8f129861368f4cf254f7f51a9fa7084b5/node_modules/rsvp/dist/rsvp.js:1077:33)
>          at GithubLocation.lookup (/Users/siclait/Documents/math-square-master-08fd93a8f129861368f4cf254f7f51a9fa7084b5/node_modules/jspm-github/github.js:381:12)
>          at /Users/siclait/Documents/math-square-master-08fd93a8f129861368f4cf254f7f51a9fa7084b5/node_modules/jspm/lib/registry.js:117:30
>          at tryCatch (/Users/siclait/Documents/math-square-master-08fd93a8f129861368f4cf254f7f51a9fa7084b5/node_modules/rsvp/dist/rsvp.js:539:12)
>          at invokeCallback (/Users/siclait/Documents/math-square-master-08fd93a8f129861368f4cf254f7f51a9fa7084b5/node_modules/rsvp/dist/rsvp.js:554:13)
>          at /Users/siclait/Documents/math-square-master-08fd93a8f129861368f4cf254f7f51a9fa7084b5/node_modules/rsvp/dist/rsvp.js:629:16
>          at flush (/Users/siclait/Documents/math-square-master-08fd93a8f129861368f4cf254f7f51a9fa7084b5/node_modules/rsvp/dist/rsvp.js:2414:5)
>          at _combinedTickCallback (internal/process/next_tick.js:95:7)
>          at process._tickCallback (internal/process/next_tick.js:161:9)
> 
> err  Error looking up github:frankwallis/plugin-typescript.
> 
> warn Installation changes not saved.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
>

**Comment by frankwallis** [comment]
Thanks for raising this, but I don't think it is actually an issue with this plugin - see https://github.com/jspm/github/issues/117 for the solution.

**Comment by Tialcis** [comment]
Thank you so much for this! I was very confused and appreciate the guidance
