### ISSUE TITLE
Error importing file from systemjs text plugin 

### ISSUE THREAD

**Issue by roguePanda** [frankwallis/plugin-typescript#21]
When I try to import a text file like this with the [SystemJS text loading plugin](https://github.com/systemjs/plugin-text), I get a compilation error about being unable to resolve an external module.
```
import html from './app.html!text';
```

I manually enabled debug logging in the TypeScript plugin and saw this in the console:
```
TypeScript Cannot find external module './app.html!text'. (TS2307)
```

It works fine when I don't try to import as a variable (i.e. `import from './app.html!text`), but then I don't have access to the text.

**Comment by frankwallis** [comment]
Yes, there doesn't seem to be a way to get this past the TypeScript compiler when using import. You will be able to do it using ```var html = require('./app.html!text')``` but that is not ideal.

I thought that the ```allowNonTsExtensions``` compiler setting might solve this (see #19) but as you say when assigning the result of the import to a variable the compiler still throws this error. It may be worth raising an issue with TypeScript to find out if this is/can be supported.

**Comment by roguePanda** [comment]
I also tried TypeScript's `amd-dependency` directive, but that didn't seem to have any effect either.

**Comment by frankwallis** [comment]
This has already been raised [here](https://github.com/Microsoft/TypeScript/issues/2709)
