### ISSUE TITLE
Not compatible with Typescript 2.6.x package

### ISSUE THREAD

**Issue by FostUK** [frankwallis/plugin-typescript#210]
Using the example setup in [this repo](https://github.com/Treri/systemjs-example/issues)

and updating the **package.json** version to the latest versions:
```json
"plugin-typescript": "^7.1.0",
"systemjs": "^0.20.19",
"typescript": "^2.6.1"
```
fails with the error message:

`Uncaught (in promise) Error: Cannot read property 'map' of undefined`

It appears to error on line 396 of plugin.js:
```javascript
return options.lib.map(function (libName) { return "typescript/lib/lib." + libName + ".d.ts"; });
```
because the **lib** part of **options** is undefined.

 I tried rolling back each and the latest typescript version seems to be the incompatibility.

Setting `"typescript": "~2.5.0"` (which will get typescript 2.5.3)
fixes this.

**Comment by frankwallis** [comment]
Thanks for raising this, it is fixed in 7.1.1
