### ISSUE TITLE
tsconfig extends

### ISSUE THREAD

**Issue by fabiandev** [frankwallis/plugin-typescript#214]
When loading compiler options from a tsconfig file, the `extends` option is not honored. Can this probably be changed in the future?

**Comment by aluanhaddad** [comment]
@fabiandev I opened #215 to implement this feature.

**Comment by fabiandev** [comment]
Awesome, that was fast. Thanks @aluanhaddad!

**Comment by frankwallis** [comment]
This is published in 8.0.0, thanks @aluanhaddad!
