### ISSUE TITLE
Error: require is not defined

### ISSUE THREAD

**Issue by jabaa** [frankwallis/plugin-typescript#216]
I can't get my app running with systemjs and plugin typescript. As far as I see the transpiler can't be loaded or can't transpile the entry file. Or it is transpiled in the wrong format.

index.html

    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8" />
      <title>Phoenix</title>
    </head>
    <body>
      <h1>Phoenix</h1>

      <script src="node_modules/systemjs/dist/system.src.js"></script>
      <script src="systemjs.config.js"></script>
      <script>
        SystemJS.import('app');
      </script>
    </body>
    </html>

systemjs.config.js

    SystemJS.config({
      typescriptOptions: {
        "module": "system",
        "noImplicitAny": false,
        "target": "es5"
      },
      packages: {
        "app": {
          "defaultExtension": "ts",
          "main": "main",
          "meta": {
            "*.ts": {
              "loader": "ts"
            }
          }
        },
        "ts": {
          "main": "plugin.js"
        },
        "typescript": {
          "main": "lib/typescript.js",
          "meta": {
            "lib/typescript.js": {
              "exports": "ts"
            }
          }
        }
      },
      map: {
        "app": "app",
        "ts": "github:frankwallis/plugin-typescript@8.0.0",
        "typescript": "npm:typescript@2.6.2"
      },
      paths: {
        "github:": "jspm_packages/github/",
        "npm:": "jspm_packages/npm/"
      },
      transpiler: 'ts'
    });

main.ts

    class Class {
      value: number;
      constructor() {
        this.value = 12;
        console.log(this.value);
      }
    };

    let myClass = new Class();

Error message in browser:

      Uncaught (in promise) Error: require is not defined
      Evaluating http://localhost:8080/jspm_packages/npm/typescript@2.6.2/lib/typescript.js
      Evaluating http://localhost:8080/jspm_packages/github/frankwallis/plugin-typescript@8.0.0/plugin.js
      Loading http://localhost:8080/jspm_packages/github/frankwallis/plugin-typescript@8.0.0/plugin.js
      Instantiating http://localhost:8080/app/main.ts
      Loading app
        at eval (typescript.js:2)
        at eval (<anonymous>)
        at evaluate (evaluate.js:106)
        at instantiate.js:394
        at dynamicExecute (register-loader.js:665)
        at doEvaluate (register-loader.js:612)
        at doEvaluate (register-loader.js:572)
        at ensureEvaluate (register-loader.js:520)
        at register-loader.js:133
        at <anonymous>

**Comment by jabaa** [comment]
I fixed the problem by downgrading plugin-typescript to 7.1.1 and installing typescript with npm instead of jspm. So I changed systemjs.config.js to 

systemjs.config.js

    SystemJS.config({
      typescriptOptions: {
        "module": "system",
        "noImplicitAny": false,
        "target": "es5"
      },
      packages: {
        "app": {
          "defaultExtension": "ts",
          "main": "main",
          "meta": {
            "*.ts": {
              "loader": "ts"
            }
          }
        },
        "phaser-ce": {
          "main": "build/phaser.js"
        },
        "ts": {
          "main": "plugin.js"
        },
        "typescript": {
          "main": "lib/typescript.js",
          "meta": {
            "lib/typescript.js": {
              "exports": "ts"
            }
          }
        }
      },
      map: {
        "app": "app",
        "phaser-ce": "npm:phaser-ce",
        "ts": "github:frankwallis/plugin-typescript@7.1.1",
        "typescript": "npm:typescript"
      },
      paths: {
        "github:": "jspm_packages/github/",
        "npm:": "node_modules/"
      },
      transpiler: 'ts'
    });

and it works.

**Comment by frankwallis** [comment]
TBH I don't think this is an issue with plugin-typescript. The original error indicates that systemjs has not detected typescript.js as a commonjs module. This could probably be fixed by adding ```"format": "cjs"``` to the configuration.

When using jspm it shouldn't be necessary to add any configuration for the installed packages 'ts' and 'typescript'. jspm will automatically fetch this configuration from the central registry and put it in a file called ```jspm_packages/npm/typescript@2.2.1.json``` (for example) and at build/runtime it will load the configuration from there. So my advice would be to simply remove the 'ts' and 'typescript' configuration altogether.

See the example projects for reference.

**Comment by jabaa** [comment]
`jspm install` doesn't work. I get deprecation warning and erros, because the paths are wrong

    The defaultJSExtensions configuration option is deprecated.
      Use packages defaultExtension instead.
    warn @ common.js:39
    fetch.js:32 Fetch API cannot load github:frankwallis/plugin-typescript@7.1.1. URL scheme must be "http" or "https" for CORS request.
    fetchFetch @ fetch.js:32
    localhost/:1 Uncaught (in promise) Error: Failed to fetch
      Instantiating github:frankwallis/plugin-typescript@7.1.1
      Loading github:frankwallis/plugin-typescript@7.1.1
      Instantiating http://localhost:8080/app/main.ts
      Loading app
        at fetchFetch (fetch.js:32)
        at instantiate.js:167
        at <anonymous>

JSPM sets the paths to

    paths: {
        "github:*": "../jspm_packages/github/*",
        "npm:*": "../jspm_packages/npm/*"
      }

I have to remove the stars and adjust the paths (because of the deprecated setting the files can't be found).

**Comment by frankwallis** [comment]
that sounds very strange, are you using jspm@0.17.0-beta?

**Comment by aluanhaddad** [comment]
JSPM 17 doesn't set those wildcards. That deprecation notice is also not new.

**Comment by jabaa** [comment]
No, I'm using 0.16.53

**Comment by aluanhaddad** [comment]
Did you update your loader (`jspm dl-loader`) by chance? You shouldn't have any issues otherwise.

**Comment by jabaa** [comment]
Update didn't change any thing. But I thing I solved my problem with plugin-typescript by customizing the systemjs config file. From here it seems like a problem with jspm.
