### ISSUE TITLE
Error loading file from typescript package in bin folder due to IIS restriction (404s)

### ISSUE THREAD

**Issue by wforney** [frankwallis/plugin-typescript#22]
The bin folder is blocked in IIS out of box so when installing your typescript plugin I got 404s when it attempted to download the typescript.js file from the bin folder of the typescript package... I'm not sure who publishes that or if you can work around it but it is a blocker for using this on IIS. Whoever maintains the typescript package you use should add a web.config allowing browsing of the bin folder or rename the bin folder something else that isn't blocked (preferred).

web.config contents to fix it below:
```xml
<configuration>
  <system.webServer>
   <security>
     <requestFiltering>
        <hiddenSegments applyToWebDAV="false">
           <remove segment="Bin" />
        </hiddenSegments>
     </requestFiltering>
   </security>
  </system.webServer>
</configuration>
```

**Comment by frankwallis** [comment]
Thanks for the information but I am using the official TypeScript package from Microsoft. So I think that you would be better to raise this issue directly on https://github.com/Microsoft/TypeScript.

**Comment by wforney** [comment]
Okay, I created an issue over there as well...

https://github.com/Microsoft/TypeScript/issues/3408
