### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by subesokun** [frankwallis/plugin-typescript#23]
When trying to use the latest jspm (master) + plugin-typescript (master) I get currently following error:

```text
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
	__exec @ system.js:1164load.metadata.execute @ system.js:2227
	linkDynamicModule @ system.js:1860
	link @ system.js:1722
	Promise.all.then.execute @ system.js:2052
	doDynamicExecute @ system.js:681
	link @ system.js:876
	doLink @ system.js:548
	updateLinkSetOnLoad @ system.js:596
	(anonymous function) @ system.js:417
localhost/:1 Uncaught (in promise) Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
	Evaluating http://localhost:8080/lib/app.ts
	Error loading http://localhost:8080/lib/app.ts!http://localhost:8080/jspm_packages/github /frankwallis/plugin-typescript@1.0.5.js
```
The file which I've tried to load was (with Babel as transpiler):
```typescript
// lib/app.ts
class Test {
  constructor() {
    console.log('Hello World!');
  }
}

var t = new Test();
```
I'm not really sure what's happening there but I've the feeling that the TS sourcecode gets directly passed into the Babel transpiler instead of running through the TS transpiler beforehand.

**Comment by frankwallis** [comment]
I'm not sure what is happening here, but it seems to be related to https://github.com/systemjs/systemjs/issues/489

**Comment by frankwallis** [comment]
I believe this is now resolved.

**Comment by vadimpopa** [comment]
Hey @frankwallis  I just upgraded the plugin from 2.1.6 to 2.3.2 and I get this error, any clue how to solve it ? thanks

**Comment by frankwallis** [comment]
Are you using ```target: 'es6'``` - try changing it to es5?

**Comment by vadimpopa** [comment]
Oh right, that's compiler related, changed that and it fixed, thanks for the hint.

**Comment by te-je** [comment]
Any options for if I want to use es6? For instance, my code uses async/await extensively, for which the current version of typescript needs to target es6.
