### ISSUE TITLE
Unsuspected import effect

### ISSUE THREAD

**Issue by b091** [frankwallis/plugin-typescript#25]
Hi,

I tried your plugin and example, and it was good ;)
But when i added jQuery import into your example it behaves weird...

![chrome console](https://cloud.githubusercontent.com/assets/228489/8540437/20dbcc0a-2486-11e5-8fd4-33ceb1d0395b.png)

index.ts
```javascript
/// <reference path="./_references.d.ts" />
import {module} from "angular";
import "./index.css";
import * as $ from 'jquery';

export var Module = module("example", [

]);

import {ExampleService} from './example-service';
import {ExampleController} from './example-controller';

Module.service("exampleService", ExampleService);
Module.controller("exampleController", ExampleController);

console.log($, $.fn);

$(() => { // this is the line of error from screen above (Error:  TypeError: $ is not a function)
  $('body').append('<div>Hello, World! </div>')
});

```
Why does it act like this? I've used jQuery imports always like this and it worked. Do you have any explanation for this case?

**Comment by frankwallis** [comment]
The issue is that you are using ```import * as $``` - this assigns all the exports from an es6 module to the $ variable. (And probably will not work for jquery as it is globally defined, not es6)

You need to do ```import $ from 'jquery'```

**Comment by b091** [comment]
Thanks.

Sadly (as you mentioned) i can't do it within TS because dts for jquery doesn't have default export :(
And even more sad is fact that it works with typescript 2 AMD without jspm ;P

**Comment by frankwallis** [comment]
There are a couple of workarounds:

1. Cheat and just use the window.$ global jquery creates:

```
/// <reference path="../jquery.d.ts" />
import 'jquery'

$(() => {
  $('body').append('<div>Hello, World! </div>')
});
```

3. Register jquery with a different name ```jspm install jqueryES6=jquery.``` Then create an ES6 compatible definition for that:
```
// jqueryES6.d.ts
/// <reference path="../jquery.d.ts" />
declare module "jqueryES6" {
   export default $;
}

import $ from 'jqueryES6'

$(() => {
  $('body').append('<div>Hello, World! </div>')
});
```
