### ISSUE TITLE
Default .ts extention configuration question 

### ISSUE THREAD

**Issue by peteruithoven** [frankwallis/plugin-typescript#28]
Great work on this plugin. I'd like to improve the readme regarding the default extension configuration, because it took me quite a while to figure out. But to suggest additional documentation I need some things cleared up. 

Please correct me if I'm wrong but this is how I understand it. Users can set `.ts` as the default extension and this plugin as the default loader in their package. This way they can use `System.import('src/app')` instead of `System.import('src/app.ts!')` and `import Person from './person'` instead of `import Person from './person.ts!'`. 

This can be done by:
1. Configuring JSPM / SystemJS to use typescript as transpiler. If this is done with `jspm init` the [typescript transpiler](https://github.com/mhegazy/TypeScript) is installed automatically. 
2. Following https://github.com/frankwallis/plugin-typescript#usage
3. Enabling SystemJS's `defaultJSExtensions` config. 
4. Adding a [packages configuration](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages). If I understand this correctly we need it in packages to apply it to importing source code from this package only? The key that's used is the name of the source folder with the .ts files. But you can also use something else and map that to your source folder using the [paths configuration](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#paths). (In the [example](https://github.com/frankwallis/plugin-typescript/blob/master/example/config.js) you use `app` and use `paths` to link that to `src`, right? 
5. For this source folder you specify `defaultExtension` and with `meta` you specify that the `ts` loader. plugin should be used for *.ts files. 
6. I need to add a typescriptOptions, even if it's empty? See https://github.com/frankwallis/plugin-typescript/issues/27

Example config. Parts like `map` are automatically added by JSPM.
``` javascript
System.config({
  'defaultJSExtensions': true,
  'transpiler': 'typescript',
  'packages': {
    'src': {
      'defaultExtension': 'ts',
      'meta': {
        '*.ts': {
          'loader': 'ts'
        }
      }
    }
  },
  'typescriptOptions': {}
  'map': {
    'ts': 'github:frankwallis/plugin-typescript@2.0.1',
    'typescript': 'github:mhegazy/typescript@v1.5-beta2',
  }
});
```

So my question is basically: 
Why are we adding this configuration in `packages`? Is this to apply it to the current package and path only? What if you want to place your source files in the root folder? I probably can't use `/` because then it would also apply to packages in `jspm_modules`? 

I guess this is mostly a SystemJS question, I'll try to suggest improvements to the packages part of SystemJS as well.

**Comment by frankwallis** [comment]
I agree its all bit complicated and error-prone at the moment (see https://github.com/systemjs/systemjs/issues/506). However I think that much of this is going to be addressed by https://github.com/jspm/jspm-cli/issues/855 which will enable the local package configuration to be put in the package.json of the module. Also the defaultJsExtensions setting is just a temporary stop-gap for back-compatibility until a better solution is implemented in the next version I think.

**Comment by peteruithoven** [comment]
Nice. 
I've also opened: https://github.com/jspm/jspm-cli/issues/930

**Comment by frankwallis** [comment]
Also I don't think it's actually necessary to have the transpiler set to 'typescript'. This loader does the same job as the typescript transpiler for ts files, so you could use traceur or babel to compile other js/jsx source if you wanted.
