### ISSUE TITLE
issue with JSPM builds

### ISSUE THREAD

**Issue by kosz** [frankwallis/plugin-typescript#32]
I have the following repo which can outline the issue : https://github.com/kosz/karma-jspm-playground

to reproduce: 
- install `npm install && jspm install` 
- then attempt to build `jspm build-sfx src/app.ts! dist/build.js`
- then run the server `npm start`
- locahost:8080/index-production.html with load with an error 

to hack and fix: 

- edit the build.js file manually 
replace 
```
(['src/app.ts!'], function(System) {
``` 
with 
```
(['src/app.ts!github:frankwallis/plugin-typescript@2.0.4'], function(System) {
```

- locahost:8080/index-production.html should now work

**Comment by frankwallis** [comment]
Strangely I am not able to reproduce, for me the build.js looks like:
```
System.register("src/app.ts!github:frankwallis/plugin-typescript@2.0.4.js", [], function(exports_1) {
  var Greeter,
      greeter;
  return {
    setters: [],
```
Are you running jspm 0.16.0-beta.3?

Also I think in 0.16 a better way to do this would be to load the 'app' package rather than directly loading its entry point. So the config would look like this:

```
System.config({
  "baseURL": "/",
  "defaultJSExtensions": true,
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "app": "src"
  },
  "packages": {
    "app": {
      "main": "app",
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    }
  }
});
```

and then you just run ```System.import('app');``` and ```jspm build-sfx app dist/build.js```
