### ISSUE TITLE
"module" option doesn't do anything

### ISSUE THREAD

**Issue by rootical** [frankwallis/plugin-typescript#34]
I am building with `buildSFX`, setting `module` as one of the options in `config.js`.
``` javascript  
 "typescriptOptions": {
    "module": "system" // setting any other option like 'commonjs', 'amd', or 'umd'.
  }
```
Produced amount of code is huge and ends up with `System.register` so it looks like a "system" option, could you please clarify? Thank you very much.

**Comment by frankwallis** [comment]
Both the built in typescript compiler and this plugin will always produce "system" format as that is what is used by SystemJS. This compiler option is ignored.

**Comment by rootical** [comment]
Thanks for the quick response. Is there any hope to add support for this?

**Comment by frankwallis** [comment]
If you can give me a valid use case for setting it to anything other than "system" then I will consider it...

**Comment by rootical** [comment]
I am building a framework on top of TypeScript and Angular, generated output should contain of:

* plain es5 module
* commonjs module
* systemjs module

That's why I need it so bad... And not only me, I believe, thank you once more.

**Comment by frankwallis** [comment]
You can get buildSFX to produce other formats using
```
builder.buildSFX('myModule.js', 'outfile.js', { sfxFormat: 'cjs' });
```

See here https://github.com/systemjs/builder#sfx-format. But the output of this plugin will still be "system", systemJS will just expose the entry point of the bundle as a commonJS module.

Otherwise it sounds like you may be better to just use the TypeScript compiler directly instead of bundling with systemJS?

**Comment by rootical** [comment]
I've tried that option and still ended up with SystemJS kind of commonjs module.

It's very pity SystemJS can't do it, would be so nice to let one tool taking care of all problems.
