### ISSUE TITLE
amd-dependency support

### ISSUE THREAD

**Issue by creaux** [frankwallis/plugin-typescript#36]
I just starting with jspm as replacement for RequireJS. I have a simple question. Does this pluggin support:

```typescript
/// <amd-dependency path="moduleName" />
```
Seems for me not, because when I trying this it is not loading related files. If it is not supported how can I overcome this? Thanks

**Comment by frankwallis** [comment]
I don't use amd-dependency, so I may be wrong about this, but...

I think that TypeScript does not remove unused imports any more, so just doing ```import "moduleName"``` should cause it to get loaded.

If that does not work it is possible to specify dependencies using the SystemJS overrides in package.json. It would look something like this:

```
"jspm": {
  /* all your usual jspm settings here */
  "overrides": {
      "shim": {
        "./index.ts": {                         // or possibly just "./index"
           "deps": [ "someModule" ]
        }
      }
   }
}
```

You can probably find some more examples of this on the JSPM repo.

**Comment by basarat** [comment]
> I think that TypeScript does not remove unused imports any more, so just doing import "moduleName" should cause it to get loaded.

Wont work. Not taking unused imports is am important tenant required for lazy loading so if you don't use it it will not get loaded

But you can do `export * from` to *imply* a dependency without using it :rose:

**Comment by frankwallis** [comment]
@basarat thanks for the info. 

So it seems to me that TypeScript should produce a different output when an amd-dependency is present for module="system" in the same way as it does for module="amd" (ie adding it to the list of injected dependencies).

**Comment by frankwallis** [comment]
Actually I think just doing ```import "moduleName"``` does work because we are transpiling with ```isolatedModules = true``` (see https://github.com/Microsoft/TypeScript/issues/4128)
