### ISSUE TITLE
TypeScript import says EISDIR

### ISSUE THREAD

**Issue by nicky-lenaers** [frankwallis/plugin-typescript#37]
I have a local project closely resembling the example code from this repo. But when I add an import statement, the builder errors with a EISDIR status. I know this means I'm pointing to a dir while I should point to anything but a dir. Any idea why this happens? If you need code, please ask and I will supply. Thanks!

**Comment by frankwallis** [comment]
A few questions:

- Can you provide the config.js and tell me what you are importing. 
- What version of jspm are you running?
- Are you type-checking and if so does the error happen when ```typeCheck``` is set to false?

**Comment by nicky-lenaers** [comment]
After some search it turned out its the same issue as #33. Fixed it by changing some filenames.

**Comment by frankwallis** [comment]
great, thanks
