### ISSUE TITLE
ES6 super call issues (because of typescript version used in this plugin) How can I change it?

### ISSUE THREAD

**Issue by robertbaker** [frankwallis/plugin-typescript#38]
So this bug has been fixed: https://github.com/Microsoft/TypeScript/issues/4118

But this plugin uses 1.5.3 before it was fixed. How can I use typescript@next with the plugin?

**Comment by frankwallis** [comment]
You can override the version of typescript used by this plugin by specifying an ```overrides``` entry in your package.json:

```
    "devDependencies": {
      "css": "systemjs/plugin-css@0.1.10",
      "ts": "frankwallis/plugin-typescript@^2.0.4",
      "typescript": "npm:typescript@1.5.3"
    },
    "overrides": {
      "github:frankwallis/plugin-typescript@2.0.4": {
        "dependencies": {
          "typescript": "npm:typescript@1.6.0-dev.20150817"
        }
      }
    }
```

**Comment by robertbaker** [comment]
thanks!

**Comment by frankwallis** [comment]
FYI - version 2.0.5 of the plugin now uses TypeScript@1.6.0-dev.20150820
