### ISSUE TITLE
Support . (dots) in filenames

### ISSUE THREAD

**Issue by larrifax** [frankwallis/plugin-typescript#39]
My naming convention uses dots in filenames, e.g. `layout.module.ts` or `admin.controller.ts`. When attempting to import such files using ES6 imports, the browser ends up requesting `layout.module` (without the `.ts` extension), which obviously ends up with a 404.

This seems like a bug in plugin-typescript, as the correct URLs are requested if using regular `.js`-files instead of typescript files.

You can verify this issue by renaming the `example-controller.ts` and `example-service.ts` to `example.controller.ts` and `example.service.ts` in your example.

**Comment by frankwallis** [comment]
Unfortunately this is a limitation in SystemJS, see https://github.com/frankwallis/plugin-typescript/issues/33. 

You can use ```import "layout.module.ts"``` but then TypeScript throws an error when type-checking the code (the code will still run ok though). Once https://github.com/Microsoft/TypeScript/issues/2338 has been addressed in TypeScript 1.6, I can change the CompilerHost to use the same resolution logic as SystemJS and this error will go away.
