### ISSUE TITLE
how to use the tsd.d.ts from tsd tool

### ISSUE THREAD

**Issue by Jandalf** [frankwallis/plugin-typescript#42]
I would like to utilize the tsd tool to maintain typescript definition files (and because this is the preferred way for vscode). but the paths that are referenced in the tsd.d.ts file are relative to the tsd.d.ts file and will resolve relative to the index.html file when loaded through your plugin.

e.g

index.html
config.js
typings/
/ tsd.d.ts (contains: \<reference path="angular2/angular2.d.ts" />)
/ angular2/
  / / angular2.d.ts
app/
 / app.ts (contains: \<reference path="../typings/tsd.d.ts"/>)

this will work for vscode or the normal ts compiler but not through systemjs.
how could I solve this problem?

**Comment by frankwallis** [comment]
Can I confirm - do you have ```typescriptOptions.resolveAmbientRefs``` set to false?

**Comment by Jandalf** [comment]
yeah that nearly did it.  but then I will get the error that
`TypeScript Cannot find module 'angular2/angular2'. (TS2307)`

but visual studio code can find it without a problem.

you could try it out:
https://github.com/Jandalf/angular2-jspm-docker-vscode-template

**Comment by frankwallis** [comment]
I think this is because app.ts does not import any references, try adding ```/// <reference path="../../typings/tsd.d.ts"/>``` to app.ts.

Its a bit of a pain at the moment you're going to need to reference that file in all your source files, I think these references should probably come from tsconfig.json, I need to have a look at loading the reference file information from there.

Incidentally angular2 is currently getting bundled from all its source files, but I think it would be a lot faster to use the prebuilt bundles. Unfortunately I can't quite find the right configuration to achieve that.

**Comment by Jandalf** [comment]
ah this did it. thank you :)

visual studio code automatically uses a reference from one file for all files. yeah that would be great, but for now tsconfig does not have such a property. (but it would be great to read all other properties out of it so we won't need a typescriptOptions section in config.js anymore)

would there be a possiblity to add an option to add a relative reference to the tsd.d.ts file to all loaded ts files, so we won't need to reference it in all of them?

hm, angular2 has many files :D loading only a single one would be huge faster. where exactly is the problem? which of the 3 (jspm, typescript-plugin, typescript-transpiler) resolves the import statements?

**Comment by frankwallis** [comment]
The problems are between systemjs and the angular bundle - the angular bundle appears to reference files in the directory below it, and I can't find the right configuration for systemjs/jspm to load it from it's current location.
