### ISSUE TITLE
Type's errors are not shown when there is a relative path import

### ISSUE THREAD

**Issue by blemoine** [frankwallis/plugin-typescript#43]
Hi,

When I make an import with a relative path (i.e. `import myModule from './myModule'`) the type's errors are not shown anymore. 
I've made a project that reproduce this problem here : 
https://github.com/blemoine/typescript-plugin-problem

To reproduce, you have to :
 * checkout the project
 * execute `npm install`
 * execute `node_modules/.bin/jspm install`
 * execute `./node_modules/.bin/jspm bundle-sfx src/app bundle.js`, which show correctly the type error
 * execute `./node_modules/.bin/jspm bundle-sfx src/app2 bundle.js`, which doesn't show the error

The only difference between app.ts and app2.ts is that in the second file, there is an import.  

In a browser, when not bundled, it's the exact same behaviour.

**Comment by frankwallis** [comment]
Thanks for raising this, there seems to be some incompatibility with TypeScript 1.6.2.

**Comment by frankwallis** [comment]
This should be fixed in 2.0.15.
