### ISSUE TITLE
TypeScript check should fail the build if errors

### ISSUE THREAD

**Issue by OliverJAsh** [frankwallis/plugin-typescript#44]
Should [`typeChecker.check`](https://github.com/frankwallis/plugin-typescript/blob/b994ee252068bac93620dbfabba9d98ee502a764/lib/plugin.js#L30) fail the build (or prevent the JS application from loading in dev) if there are errors?

**Comment by frankwallis** [comment]
It is deliberate to not error the build on type-checking errors, but I can see how it might be correct for e.g. production builds. Perhaps I should add a 'strict' mode which throws on error?

**Comment by frankwallis** [comment]
I have made a change so that if you use ```typeCheck: "strict"```, then the build will fail if there are compiler errors. Let me know if you have any issues, thanks. It's included in 2.1.0.
