### ISSUE TITLE
multi option scopes

### ISSUE THREAD

**Issue by druppy** [frankwallis/plugin-typescript#49]
Hi ...

It is possible to setup options for typescript using the ```optionTypescript``` to element in the config block. Will this remain to to be the case, or will this be moved down to the ```package -> meta``` section, or will we be able  to do both ?

The new ```tsx``` format, could be nice to only enable for a single package, as it change some of the language when put into use. It could therefor be nice to setup this option for only one single "view" package.

Is this possible at the moment or are the any plans in this regard ?

/BL

**Comment by frankwallis** [comment]
This is really a question for SystemJS, but I agree from a TypeScript perspective it makes sense to allow different configuration options for different packages. There are plans to allow package configuration to be specified within the package (https://github.com/jspm/jspm-cli/issues/855) which may enable this but I'm not certain.

**Comment by druppy** [comment]
Ok, thanks for the link ... I will keep an eye on this issue. I quess this plugin just ask for the typescript options and systemjs/jspm collect them, and if it needs to be found in the meta or package scope, it is the systemjs/jspm that handle this. Make perfect sense ...
