### ISSUE TITLE
Error: ts is not defined

### ISSUE THREAD

**Issue by OliverJAsh** [frankwallis/plugin-typescript#50]
I have installed this plugin and added it to my jspm app:

``` json
  // TS
  "packages": {
    "app": {
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    }
  },
  typescriptOptions: {
    "typeCheck": "strict"
  },
```

When I run this file:

``` ts
// app/main.ts
var strIdentity = function (x: string) {
    return x;
};

window.alert(strIdentity([]));
```

Everything works, but I get this error in my console (as well as type checking errors):

```
Unhandled promise rejection ReferenceError: ts is not defined
```

![image](https://cloud.githubusercontent.com/assets/921609/10732381/b2d677d2-7bf1-11e5-9933-5c0833ad2218.png)

**Comment by frankwallis** [comment]
Thanks, that is now fixed in 2.1.3.
