### ISSUE TITLE
Angular2 bundled example - BaseException {message: "Token must be defined!"...

### ISSUE THREAD

**Issue by edvlucas** [frankwallis/plugin-typescript#52]
When I try to run the bundled angular2 example via:

```
gulp bundle (or jspm bundle ...)
gulp example 
navigate to http://127.0.0.1:8080/index-bundle.html
```

I am getting the following exception:

```
BaseException {message: "Token must be defined!", stack: "Error: Token must be defined!↵    at new BaseExcep…ry (http://127.0.0.1:8080/build/build.js:4231:22)"}BrowserDomAdapter.logError @ browser_adapter.js:81(anonymous function) @ application_ref.js:166run @ core.js:70(anonymous function) @ ng_zone.js:174NgZone.run @ ng_zone.js:137PlatformRef_._initApp @ application_ref.js:147PlatformRef_.application @ application_ref.js:129commonBootstrap @ application_common.js:56bootstrap @ application.js:25(anonymous function) @ index.ts:16arguments.(anonymous function) @ functions.js:19(anonymous function) @ core.js:56run @ core.js:70zoneBoundFn @ core.js:50
ng_zone.js:255 ## _notifyOnError ##
ng_zone.js:256 TypeError: Cannot read property 'get' of undefined
    at http://127.0.0.1:8080/build/build.js:25407:47
    at Zone.run (http://127.0.0.1:8080/build/build.js:1851:19)
    at Zone.run (http://127.0.0.1:8080/build/build.js:16212:34)
    at NgZone.run (http://127.0.0.1:8080/build/build.js:16174:36)
    at ApplicationRef_.bootstrap (http://127.0.0.1:8080/build/build.js:25402:18)
    at Object.commonBootstrap (http://127.0.0.1:8080/build/build.js:25532:38)
    at Object.bootstrap (http://127.0.0.1:8080/build/build.js:25569:33)
    at http://127.0.0.1:8080/build/build.js:26893:29
    at arguments.(anonymous function) (http://127.0.0.1:8080/build/build.js:1905:26)
    at http://127.0.0.1:8080/build/build.js:1837:25
application_ref.js:243 Uncaught TypeError: Cannot read property 'get' of undefined
```

The dynamically loaded example (index.html) works fine. Any ideas?

**Comment by frankwallis** [comment]
I am seeing this too, but I don't know why its happening. This error has also been seen when using webpack http://stackoverflow.com/questions/32569473/baseexception-in-angular2with-es6-webpack. I will keep investigating.

**Comment by edvlucas** [comment]
Hi Frank,

Thanks for confirming the issue, good to know that it is not related to my
environment. I will play with it a bit too and if I find a solution I will
let you know.

My next idea is to exclude angular, zone and reflect from the bundle, load
them manually and then see what happens...

Greetings,

Eduardo

**Comment by frankwallis** [comment]
Thanks Eduardo - FYI it has also been reported here, with full repro: https://github.com/angular/angular/issues/4999

**Comment by frankwallis** [comment]
It looks like it is happening when trying to register/instantiate the 'LifeCycle' class. The constructor dependencies come through as an array with a single undefined item. When loading dynamically the dependency is populated with the 'ExceptionHandler' constructor.

I wonder if it is also related to this: https://github.com/angular/angular/blob/master/gulpfile.js#L953

**Comment by frankwallis** [comment]
I have just updated to angular2@2.0.0-alpha.45 and systemjs-builder@0.14.10 and it looks like it has been fixed.

**Comment by edvlucas** [comment]
The upgrade to alpha.45 also solved my problem. Thanks for the feedback and your great plugin.
