### ISSUE TITLE
How to avoid having compiler's error within an editor ?

### ISSUE THREAD

**Issue by Xample** [frankwallis/plugin-typescript#56]
I cloned the git's repository, and ran all the procedure for the example angular2 till
```jspm bundle-sfx src build/build.js```
Which produce the expected build.js file.

However when I do open the project within Atom or Webstorm, I do face the
"Corresponding file not included in tsconfig.json" error when I do
```import {bootstrap} from 'angular2/angular2';```

Of course, the actual folder is ```angular2@2.0.0-alpha.45/angular2``` and I could include within the tsconfig.json file the path to the root ```jspm_packages/npm folder``` but then jspm will not compile anymore.

Is this a current limitation to the model or I am doing it wrong ? Is there a special configuration trick or a workaround to apply ?

**Comment by frankwallis** [comment]
This is a current limitation - the resolveAmbientRefs stuff is not supported in editors and so you get these errors.

I am working on a new release where plugin-typescript will support the new resolution model implemented in TypeScript (see [here](https://github.com/Microsoft/TypeScript/issues/2338) and [here](https://github.com/Microsoft/TypeScript/issues/5039))

Initially I will be implementing support for plugin-typescript to read the ```typings``` field in angular2/package.json to locate angular.d.ts correctly and the resolveAmbientRefs stuff will be deprecated.

A workaround for the moment would be
1) Turn off ```resolveAmbientRefs```
2) Add a reference in tsconfig.json to "jspm_packages/.../angular2.d.ts"
3) Remove the angular2 references from src/_references.d.ts

**Comment by Xample** [comment]
Thank you for your answer. Basically I am looking for a workflow to build a .js library using typescript + external modules. The purpose of jspm being obviously to be able to easily import those modules from different sources. Would naming the package with  ```jspm install myname=npm:underscore``` helpful in someway ?

**Comment by frankwallis** [comment]
The name of the module being imported should match whatever the name of the module is in the declaration file, so if you do ```jspm install myname=npm:underscore``` then you would need a declaration file containing:

```
declare module 'myname' {
   export function groupBy(...)
}
```
so I don't think it will help particularly to rename the modules.

I would recommend that you use [tsd](https://github.com/DefinitelyTyped/tsd) to install the external declarations, and then include a reference to ```typings/tsd.d.ts``` in your tsconfig.json.
