### ISSUE TITLE
Unexpected token import with 2.2.1

### ISSUE THREAD

**Issue by mjw56** [frankwallis/plugin-typescript#57]
Hi,

Seeing an error that import is not recognized when using latest 2.2.1 version. I'm using react, tsx and typescript 1.6.2.

```js
Uncaught SyntaxError: Unexpected token import
Uncaught (in promise) Uncaught SyntaxError: Unexpected token import
	Evaluating http://localhost:3002/example/app.tsx
	Error loading http://localhost:3002/example/app.tsx
```

If I switch back to 2.1.6 everything is working fine. I had been using this setup fine for a couple weeks so I was surprised when it started throwing this error after I fresh re-install of jspm_packages.

 I'm not sure if something has changed in the way the project should be configured since that release. I can share my project setup if it helps. Thanks.

**Comment by frankwallis** [comment]
Hi, sorry about that - it seems that the parsing of the ```target``` option changed from 2.1.6 to 2.2.0. This is the same issue as https://github.com/frankwallis/plugin-typescript/issues/54 I think. The easiest fix will be to set ```target: 'es5'``` in ```SystemJS.typescriptOptions```.

**Comment by mjw56** [comment]
It's ok, setting ```target: 'es5'``` worked.

Thanks for the help and for this project. :)
