### ISSUE TITLE
Usage instructions without jspm

### ISSUE THREAD

**Issue by guybedford** [frankwallis/plugin-typescript#59]
As part of moving towards making this the recommended way of handling TypeScript in SystemJS, would it be possible to include some instructions for use with SystemJS without jspm?

**Comment by frankwallis** [comment]
Yes I can add some instructions and maybe an example project, but I don't really know how to do this myself - can you give me quick rundown?

**Comment by guybedford** [comment]
Thanks, I'm working on the Traceur and Babel plugins - will send links when I make progress to show the pattern on those if that helps?

**Comment by guybedford** [comment]
See https://github.com/systemjs/plugin-babel for an example of native SystemJS instructions.

**Comment by frankwallis** [comment]
I have added a section to the readme on installing without jspm.

**Comment by guybedford** [comment]
:+1:
