### ISSUE TITLE
Does this plugin support source map?

### ISSUE THREAD

**Issue by jack4it** [frankwallis/plugin-typescript#60]
What does the debugging experiences in browser look like?

**Comment by frankwallis** [comment]
yes, this plugin supports source-maps so in the browser you can set breakpoints and step through the original typescript source code.

If you are compiling in the browser then any errors should also link to the correct location in the original source file.

**Comment by jack4it** [comment]
Awesome, I also just tried it out, works perfectly!

I have another side question. I'm trying to write a systemjs plugin, but facing a hard time of "require" a npm module. The require always tries to resolve the node module from right at the root of the app, instead of node_modules folder. Do you have any ideas of why?

Thanks!

**Comment by jack4it** [comment]
Solved my problem! :) https://github.com/systemjs/builder/issues/409
