### ISSUE TITLE
Bundle in angular2 project doesn't work

### ISSUE THREAD

**Issue by lee-tunnicliffe** [frankwallis/plugin-typescript#62]
I can't quite see why at the minute. The error I get is:

throw new Error('Unhandled promise rejection.\n' + reason && reason.stack ||
        ^
Error: Error: ENOENT, open 'c:\Projects\plugin-typescript-new\example\angular2\jspm_packages\github\frankwallis\example-service@master\angular2\bundles\typings\angular2\angular2.d.ts'

**Comment by frankwallis** [comment]
Thank you, I had left a <reference .../> tag in the [example-service](https://github.com/frankwallis/example-service) submodule which was relying on ```resolveAmbientRefs```. I have removed it now.
