### ISSUE TITLE
Disable __moduleName wrapping for build

### ISSUE THREAD

**Issue by guybedford** [frankwallis/plugin-typescript#65]
This `__moduleName` variable is a tricky one. It is supposed to be the canonical name on build, which is handled via the transpiler, which I'm tracking in https://github.com/systemjs/builder/issues/416, but in the mean time it may just be worth disabling this on build as it is currently outputting file URLs I believe. See https://github.com/jspm/project/issues/32.

**Comment by frankwallis** [comment]
Ok I'll do that - is there a particular flag/setting in SystemJS which I can use to detect when the plugin is being run in build mode?

Also I have a question about ```__moduleName``` - this plugin needs to use ```__moduleName``` to resolve ```typescript/lib/lib.d.ts``` when compiling - see [here](https://github.com/frankwallis/plugin-typescript/blob/master/src/factory.ts#L93). That code ought to read:

```
// TODO - remove this when __moduleName is available
return _resolve(host.getDefaultLibFileName(), moduleName)
			return _resolve('ts', '')
				.then(moduleName => {
					 
				})


Currently it is provided by the built-in transpiler, but when that gets deprecated in 0.17 SystemJS provide the __moduleName wrapper?

**Comment by guybedford** [comment]
Yes - you can check `loader.builder == true` where `loader` is the `this` reference of the hooks. See https://github.com/systemjs/plugin-babel/blob/master/babel.js#L110.

In terms of answer the other question - can you clarify what environment you transpile the transpiler itself through?

**Comment by frankwallis** [comment]
I'm pre-transpiling it with TypeScript into es5/commonjs.

**Comment by guybedford** [comment]
@frankwallis so the `__moduleName` would have to be provided by the precompilation system itself pending https://github.com/systemjs/builder/issues/416.

**Comment by frankwallis** [comment]
ok i'll wait for that.

**Comment by frankwallis** [comment]
As of plugin-typescript@2.3.2, __moduleName is not output in build mode.

**Comment by guybedford** [comment]
:+1:
