### ISSUE TITLE
tsc -> babel -> es5?

### ISSUE THREAD

**Issue by laurelnaiad** [frankwallis/plugin-typescript#68]
Hi,

I'd love to use plugin-typescript for an in-browser TSC -> Babel -> ES5 workflow. 

I hunted through the open and closed issues here and there are several clues lying around in the closed issues here suggesting that people are doing this in the System.js loader context.... and yet I can't seem to make it work.

Is there a way to do it?

Here is my slimmed down repro of my attempt: https://github.com/laurelnaiad/pt-test

Any guidance on where I've gone wrong?

Thanks!

**Comment by frankwallis** [comment]
I have released 2.4.0 which will now handle this setup, you will need to set ```{ target: 'es6', module: 'es6' }``` in your typescript configuration. Let me know if you find any problems.

**Comment by Bartzy** [comment]
Why the module needs to be set to 'es6' and not 'system'?

Thanks.

**Comment by laurelnaiad** [comment]
My guess is that leaving the module in es6 form helps System.js to know that it should run babel over the output from tsc?

**Comment by Bartzy** [comment]
But then, how TypeScript knows how to load stuff like import $ from 'jquery'?

@laurelnaiad, Can you perhaps share your setup? And how do you later build a standalone from that (I too am interested in an in-browser TS -> Babel (ES6) -> ES5 for development).

I want to use TypeScript for the type definitions only, and not as a transpiler. Tried using Flow but the lack of 3rd-party definitions is an immediate no-go for me...

thanks!

**Comment by laurelnaiad** [comment]
I can go back and check what I was doing when I was using this setup. Will post back when I have time to do that. 

I ended up finding that having the browser do all of this transpiling (and downloading/loading of transpilers/shims, esp. browser.js) was much slower than using gulp-typescript and gulp-babel. Also, going the build-time tranpspile path got me to to working sourcemaps...

**Comment by Bartzy** [comment]
Why do you care that is was slower though, if it's only happening on refresh? Did it really slow down your development cycle?

Thanks!

**Comment by laurelnaiad** [comment]
I care that it was slower because it's happening on refresh! :) Yes. 

Our project has always been intended to be delivered as a series of optimized jspm modules, and so the build-time transpile needed to be addressed at some point one way or the other.

My project re-transpiles in <1 second with the gulp utilities (including gulp-typescript in project/incremental mode)... whereas by the time browser.js was parsed/run, almost 4 seconds had elapsed. In a "watch mode" scenario where you want to see your changes shortly after saving a .ts file, the different between <1 second and 4 seconds is huge.

**Comment by laurelnaiad** [comment]
I should note: I would ascribe the vast majority of the delays to babel, **not** this plugin, which performed quite well on its own.

**Comment by Bartzy** [comment]
And how does SystemJS/JSPM is working with gulp-typescript and gulp-babel? What is the transpiler that is configured for it?

**Comment by laurelnaiad** [comment]
Sorry, just checked my git history.. I didn't keep the branch where I was using this combination, but if I recall correctly it worked by setting the system.js transpiler to babel (`transpiler: 'babel'`), and then configuring this plugin as it's documented to be configured in the readme, and following @frankwallis' suggestion regarding tsconfig settings. I feel like I might have exprimented with the module setting. I don't remember where I landed, but it doesn't really matter -- use the module setting that works, it's a non-issue in the long run. :)

Aside from having those two transpiler co-configured (with babel as the "officially" configured transpiler and plugin-typescript mapped as its documented, everything else was vanilla system.js. 

To make a long story short, there was nothing complicated about setting this up, once @frankwallis made it work.

Regarding other questions not on-topic for plugin-typescript, please feel free to email me off-thread.
