### ISSUE TITLE
tsc-> babel -> es5: sourcemaps?

### ISSUE THREAD

**Issue by laurelnaiad** [frankwallis/plugin-typescript#69]
Hi Frank,

Re: https://github.com/frankwallis/plugin-typescript/issues/68 ...

Thank you for helping out with the tsc->babel->es5 pipeline.

I do see it getting both transpilers into the mix with your suggested configuration.

I can't seem to get sourcemaps to work for these files, though.

I only see a !transpiled file in Chrome, and it is lacking all sourcemap information.

I wonder if the way plugin-typescript is dealing with sourcemaps is throwing off babel or vice-versa? Or have I just misconfigured it?

I pushed my changes to https://github.com/laurelnaiad/pt-test again. Could you take a look? You can just `serve` the repo and set breakpoints on the console.log statements in index.html to see what I'm talking about.

Thanks!
Daphne

**Comment by frankwallis** [comment]
Unfortunately I think this is a known issue in Babel 5, I did look into it but there was no simple workaround.

SystemJS 0.17 will have a Babel 6 plugin, so I will revisit it then, which I expect to be some time in January.

**Comment by revov** [comment]
Is the problem with sourcemaps present only for the "tsc-> babel -> es5" approach? I cannot make it work even with `transpiler: false` and `"target": "es5"`. No matter what combination of configurations I tried I only see !transpiled files in Chrome console and the base64 encoded sourceMappingURL at their bottom points to `[object Object]`:

```
//# sourceMappingURL=data:application/json;base64,W29iamVjdCBPYmplY3Rd
```

Meanwhile there is no issue with the sourcemaps if using JSPM's built-in typescript transpiler. However, it has many other disadvantages, for example problems with bundling via JSPM.

P.S.: I am following the angular2 example from the examples folder.

**Comment by laurelnaiad** [comment]
I don't recall having sourcemaps problems unless I added babel to the mix.

**Comment by erkez** [comment]
It is also not working for me. I get exactly the same source mapping as @revov explains above. I am not using Babel. The built-in Typescript transpiler works correctly.

**Comment by frankwallis** [comment]
@erkez , @revov I have applied a fix for the source-maps in 2.4.7.
The issue still remains with the babel workflow however.

**Comment by revov** [comment]
Thank you, @frankwallis. I can confirm that sourcemaps now work properly if not using babel.

**Comment by frankwallis** [comment]
From version 2.5.0 onwards, the babel source maps should now be working (see https://github.com/frankwallis/plugin-typescript/pull/86) - thanks @brn.
