### ISSUE TITLE
Consider tagging on GitHub

### ISSUE THREAD

**Issue by guybedford** [frankwallis/plugin-typescript#7]
It could be worth not publishing to npm and just tagging this on GitHub if you prefer.

**Comment by guybedford** [comment]
I was able to install from GitHub with `jspm install ts=github:frankwallis/plugin-typescript@master`.

If there were `v0.1.0` tags, these would install as versions in jspm.

**Comment by frankwallis** [comment]
created tag 0.5.5. 

Once it's working can it be added to the jspm registry so you can just do ```jspm install plugin-typescript```?

**Comment by guybedford** [comment]
@frankwallis yes exactly, or even just under `ts` to easily allow `import 'file.ts!'`.

**Comment by frankwallis** [comment]
created pull-request https://github.com/jspm/registry/pull/218
