### ISSUE TITLE
Source maps broken in 2.4.2

### ISSUE THREAD

**Issue by compeek** [frankwallis/plugin-typescript#72]
I upgraded to 2.4.2 and the source maps no longer work. In Chrome I only see .ts files, but they contain the compiled JavaScript, and the original TypeScript is nowhere to be found. There are no .ts!transpiled files.

**Comment by frankwallis** [comment]
Thanks, fixed in 2.4.3

**Comment by compeek** [comment]
Thank you for the quick fix! Excellent work on this plugin.
