### ISSUE TITLE
Support for angular2.beta0

### ISSUE THREAD

**Issue by jvanharn** [frankwallis/plugin-typescript#74]
When upgrading the _angular2_ example to beta.0, and adjusting the imports (angular2/angular2 -> angular2/core etc. see [alpha.53 breaking changes](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-2)), the angular2 example fails as following:
```
[08:38:03] Using gulpfile /vagrant/angular2/gulpfile.js
[08:38:03] Starting 'bundle'...
TypeScript file:///vagrant/angular2/src/index.ts:1:25
TypeScript Cannot find module 'angular2/platform/browser'. (TS2307)
TypeScript file:///vagrant/angular2/src/index.ts:2:42
TypeScript Cannot find module 'angular2/core'. (TS2307)
TypeScript file:///vagrant/angular2/src/example-component.ts:1:56
TypeScript Cannot find module 'angular2/core'. (TS2307)
Build complete, go to http://127.0.0.1:8080/index-bundle.html
[08:38:07] Finished 'bundle' after 4.28 s
```
It can no longer find any imports. Is this something you can fix with the automatic typings resolving? Or would you suggest that this may be an issue with System.js/JSPM (or Angular2)?

**Comment by masaeedu** [comment]
@jvanharn Having the same problem, this might be because you also have `moduleResolution` in your tsconfig.json set to `node`.

**Comment by jvanharn** [comment]
For those facing a similar problem: Typescript can't find the modeles because it was searching for them in node_modules, however mine were in jspm_modules. I fixed this by installing angular2 again, but with the normal npm install, (though it isn't used, apart from compilation). It is a known bug in Typescript: https://github.com/Microsoft/TypeScript/issues/5039 .

So this issue can be closed, thanks for your patience though!

**Comment by frankwallis** [comment]
Thanks for the update
