### ISSUE TITLE
transpiler true difference

### ISSUE THREAD

**Issue by blackjid** [frankwallis/plugin-typescript#76]
I just want to know whats the difference between using this plugin or enabling the `transpiler: 'typescript` in the jspm config.js

here https://github.com/frankwallis/plugin-typescript/issues/59 @guybedford mention that this plugin would be the recommended way to use typescript with jspm and systemjs... but what's the difference?

**Comment by frankwallis** [comment]
The main difference is that the built-in transpiler does not type-check your code, type-checking can be enabled in this plugin by setting the ```typeCheck``` option to true. If you just want to transpile your code and run a separate type-checker (e.g. ```tsc -w``` with ```noEmit``` option) then there is little functional difference between them.

There is work being done to remove the built-in transpilers (typescript, babel, traceur) from jspm entirely, and make them available as external plugins, and that is why @guybedford recommends to use this plugin.

**Comment by blackjid** [comment]
thanks @frankwallis

**Comment by djindjic** [comment]
@frankwallis I'm going through the issues and found this question also interesting for me. It's a little confusing for me at this moment why do you have `transpiler: "typescript"` in [this](https://github.com/frankwallis/plugin-typescript/blob/8ecbf6bbc926796f931b3234d70ae7f57d20d59e/example/angular/config.js#L4) example if we are trying to do it with plugin?

Thanks!

**Comment by frankwallis** [comment]
I've added ```systemjs-hot-reloader``` which is published in es6 module format, so I am using the default transpiler to transpile that to es5.
The package configuration means that everything in ```src``` will go through plugin-typescript, and I suppose I could add more package configuration for systemjs-hot-reloader etc, but this was just easier. In jspm 0.17 it is possible to set the default transpiler to be plugin-typescript and then the built-in one is not used at all.
