### ISSUE TITLE
Declaration file

### ISSUE THREAD

**Issue by nillis** [frankwallis/plugin-typescript#77]
How would you generate a declaration file when creating a jspm bundle?

EDIT
Maybe I should clarify my goal behind the question: I want to be able to make use of full intellisense when importing external modules 
f.e. external-services in https://github.com/frankwallis/plugin-typescript/tree/master/example/angular2

When I import this external module (external-services), I want to be able to determine the operations on the ExampleService with intellisense. What is the most convenient way atm to accomplish this? 
https://github.com/frankwallis/plugin-typescript/blob/master/example/angular2/src/example-component.ts

**Comment by nillis** [comment]
Same question as in this post: http://stackoverflow.com/questions/33702567/how-to-import-external-npm-module-with-typescript-declarations-using-jspm

**Comment by frankwallis** [comment]
Also see this one https://github.com/frankwallis/plugin-typescript/issues/73 and the issues linked to from there. TLDR it is difficult at the moment but will hopefully get easier.

**Comment by nillis** [comment]
I managed to get things working quite well now without having to create manual declaration files with the typings package (https://github.com/typings/typings) you suggested else where. I'll upload the sample when I'm home. 

If there is anyhting I can help or contribute to make things easier (with TS, with your plugin, with SystemJS-TS integration, with JSPM, ...), I'm glad to help. All these projects are pure diamonds which will be fine-tuned in the coming months. Thanks to you for creating this plugin!

**Comment by frankwallis** [comment]
Thanks, I think things are pretty under control at the moment, but I appreciate your interest. Just reporting/fixing issues and suggesting features is very useful. I am in the process of doing some fairly major changes to support hot-reloading, so you want to give them a go and let me know if you have any problems that would be a help. I will be pushing them to master today or tomorrow.

**Comment by nillis** [comment]
Great, i'll test it under my current application!
