### ISSUE TITLE
Jspm bundle arithmetics

### ISSUE THREAD

**Issue by r57** [frankwallis/plugin-typescript#79]
There is a problem when building dependency bundles with `plugin-typescript`. I tried to demonstrate in  https://github.com/r57/jspm-ts-bundle

When I bundle by `jspm bundle 'src/**/* - [src/**/*]' build/built.js` I expect to get bundle without actual `src` package modules but they are indeed included. At least all modules apart from entry point `boot.ts`. Actual output:

```
      Building the bundle tree for src/**/* - [src/**/*]...
     
       github:jspm/nodelibs-process@0.1.2
       github:jspm/nodelibs-process@0.1.2/index
       npm:lodash@3.10.1
       npm:lodash@3.10.1/index
       npm:process@0.11.2
       npm:process@0.11.2/browser
       src/boot.ts!github:frankwallis/plugin-typescript@2.4.5
       src/component.ts
       src/component.ts!github:frankwallis/plugin-typescript@2.4.5
```
(note the `boot.ts` is missing, but other modules stays)

How to get rid of those `src/*` files?

/cc @guybedford

**Comment by frankwallis** [comment]
It looks to me as though [systemjs-builder](https://github.com/systemjs/builder) may not be handling filenames with the ```!plugin``` extension quite right. I have updated your example [here](https://github.com/frankwallis/jspm-ts-bundle) to demonstrate the issue happens with any plugin, and is not specific to plugin-typescript. I think you should raise this over on the systemjs-builder repository please.

**Comment by guybedford** [comment]
Yes this is a known bug - https://github.com/systemjs/builder/issues/447.

**Comment by frankwallis** [comment]
@guybedford ok thanks, I have added a comment on that issue.
