### ISSUE TITLE
js file not found

### ISSUE THREAD

**Issue by guybedford** [frankwallis/plugin-typescript#8]
When I use this plugin, for some reason I'm getting GET file:///Users/guybedford/Projects/jspm-cli/sandbox/test.ts.js net::ERR_FILE_NOT_FOUND.

To fix this I had to add `load.address = address.substr(0, address.length - 3);` into the locate function in `plugin.js:83` as otherwise it will add the js extension. I know it's not ideal.

Do check you're running the latest jspm for this work.

**Comment by frankwallis** [comment]
I have been getting around that by removing the "*" -> "lib/*.js" mapping in config.js. This is the issue I was referring in the original thread where systemjs is maybe a bit over-zealous about all files getting a '.js' extension. (it's kind of related to https://github.com/systemjs/systemjs/issues/113 & https://github.com/ModuleLoader/es6-module-loader/issues/169 I think)

**Comment by guybedford** [comment]
Yes that functionality will be added in the next version of SystemJS - you can follow this at https://github.com/systemjs/systemjs/issues/319.

**Comment by frankwallis** [comment]
I've put that into the locate and it's working well. Fixed in 0.5.7.
