### ISSUE TITLE
Incorrectly resolved typings file path

### ISSUE THREAD

**Issue by kostko** [frankwallis/plugin-typescript#80]
If a `package.json` of an external dependency includes a `typings` declaration in the form of:
```json
"typings": "Rx.d.ts"
```

then the plugin will use an incorrect path and fail with an error like (note that the bundling process will not fail despite a compiler failure and strict type checking enabled):
```
TypeScript ENOENT, open '/path/to/toplevel/dir/Rx.d.ts'
```

Changing the `typings` field to read `./Rx.d.ts` works correctly. To reproduce, just check the `rxjs` package.

**Comment by frankwallis** [comment]
Thanks, this should be fixed in 2.4.6
