### ISSUE TITLE
Translate should return the source only

### ISSUE THREAD

**Issue by guybedford** [frankwallis/plugin-typescript#81]
I've just been doing some testing of this plugin, and noticed this now.

Translate takes as input the load record, then returns a source.

Currently this plugin seems to return the full load record at https://github.com/frankwallis/plugin-typescript/blob/master/src/plugin.ts#L52.

This may have been working in SystemJS by mistake, but that shouldn't be the case.

**Comment by frankwallis** [comment]
ok I'll get that changed. Let me know if there are any other changes I need to make for 0.17

**Comment by frankwallis** [comment]
Thanks, fixed in 2.4.6

**Comment by guybedford** [comment]
Great thanks, all seems to be working in the 0.17 now as far as I can tell. Beta will be published this evening.

**Comment by frankwallis** [comment]
Excellent, I look forward to giving it a try
