### ISSUE TITLE
Stuck after plugin & systemjs upgrade

### ISSUE THREAD

**Issue by vadimpopa** [frankwallis/plugin-typescript#82]
Hey @frankwallis, I would need you help again, with some thoughts on what could be the reason on browser hang at app loading (https://github.com/vadimpopa/ionic2-jspm-seed). It's stuck at app.js at Ionic import. If I import something from the ./app/ , I can see the import transpilled ok. I'll dig more within the next days, but wondering if you could take a look on the configs and see if I did something wrong.Thanks

**Comment by vadimpopa** [comment]
I've figure out that it's a systemjs problem, is looping while trying to import ionic. You an close the question/issue.

**Comment by frankwallis** [comment]
ok thanks
