### ISSUE TITLE
inlinesourcemaps are dropped in system.js

### ISSUE THREAD

**Issue by mikeyoon** [frankwallis/plugin-typescript#83]
If I set the inlineSourceMap to true, it looks like the resulting sourcemap is wiped due to it being converted into a JS object, but system.js seems to expect a string, so it will print out the base64 encoding of [object object].

Here's what system.js is doing.

```'\n//# sourceMappingURL=data:application/json;base64,' + btoa(unescape(encodeURIComponent(load.metadata.sourceMap))) || '')```

In plugin.js, it parses the sourcemap json, which won't work with system.js.

```load.metadata.sourceMap = JSON.parse(result.sourceMap);```

Looks like the change to parse the sourceMap JSON is for supporting other module loaders, so probably would need some check I guess beforehand.

**Comment by frankwallis** [comment]
Thanks for raising this, I have applied a fix in 2.4.7.
