### ISSUE TITLE
JSPM bundling: Typings not found

### ISSUE THREAD

**Issue by peterjuras** [frankwallis/plugin-typescript#84]
Hi!

I'm trying to enable type check, but I always get errors when bundling with JSPM. I don't get these errors when I use your plugin directly in the browser. These are the errors:

```bash
TypeScript ENOENT: no such file or directory, open '/usr/local/src/systemjs-test/typescript/lib/lib.es6.d.ts'
TypeScript ENOENT: no such file or directory, open '/usr/local/src/systemjs-test/typings/tsd.d.ts'
```

The bundling works, but the types are not checked during the bundling.

This is my folder structure:

root/package.json (where I execute jspm)
root/src/client/app/config.js (systemjs config)
root/src/client/app/jspm_packages (all jspm packages)
root/src/client/app/typings (my typings, including tsd.d.ts)
root/src/client/app/src/index.tsx (the bundle entry point)

If I execute jspm in the root/src/client/app/ directory, then it is able to find the tsd.d.ts typings file and all referenced typings except lib.es6.d.ts

The lib.es6.d.ts file can be found within jspm_packages/npm/typescript@version/lib directory, but I don't want to hardcode the version and this has not been necessary before.

What am I doing wrong?

This is my config.js:
```js
System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  typescriptOptions: {
    "jsx": "react",
    "typeCheck": true,
    "files": [
      "typings/tsd.d.ts"
    ],
    "tsconfig": false
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  packages: {
    "src": {
      "main": "index.tsx",
      "defaultExtension": "tsx",
      "meta": {
        "*.js": {
          "loader": "ts"
        },
        "*.jsx": {
          "loader": "ts"
        },
        "*.ts": {
          "loader": "ts"
        },
        "*.tsx": {
          "loader": "ts"
        }
      }
    }
  },
// ...
```

**Comment by peterjuras** [comment]
on a similar note, setting tsconfig to false does not work when bundling, it will still parse the tsconfig.json of the root directory. (Not sure if this is what leads to the errors)

**Comment by peterjuras** [comment]
After further investigation, the bundling started to include these errors with jspm 0.16.20 (implicitly using systemjs-builder 0.15.0), where as everything worked fine with jspm 0.16.19 (using systemjs-builder 0.14.15).

@guybedford Do you have an idea on what change might have caused this?

**Comment by peterjuras** [comment]
This issue is also affecting all three examples of this repository. You can replicate it, by setting typeCheck to true (or strict like the in the angular example) in the config.js and running 

```bash
jspm bundle src/index test/a
```

You will see the following error message at the top of the bundling output:
```bash
Building the bundle tree for src/index...
TypeScript ENOENT: no such file or directory, open '/usr/local/src/plugin-typescript/example/angular/typescript/lib/lib.es6.d.ts'
```

**Comment by nillis** [comment]
Same problem here. And although the typecheck is set to strict, it don't show compile errors (except the missing typings errors). 
I guess it had something todo with the change in SystemJS to use this plugin when the transpiler is set to typescript.

**Comment by frankwallis** [comment]
Thanks for raising this, the problem is that the plugin is no longer able to correctly normalize 'typescript/lib/lib.es6.d.ts' which it needs to perform the type-checking. I don't understand why it 
has now started failing, but I do believe I have a fix which I will look to release at some point this week.

**Comment by peterjuras** [comment]
That's great to hear! Thanks for looking into this!

**Comment by nillis** [comment]
Great!

**Comment by GauSim** [comment]
+1

**Comment by frankwallis** [comment]
I have released a fix/workaround for this in 2.4.9.

I am still not sure what the actual issue was, but I have changed the output format of plugin-typescript to ```system.register``` format and things seem a lot happier. I think there may be an issue with the systemjs normalization when bundling, but why the format of the plugin would affect that I don't know.

All 3 example projects should now bundle.

**Comment by peterjuras** [comment]
Thanks a lot, your fix not only takes care of the lib.es6.d.ts issue but also correctly resolves typings from the specified baseURL.

Thanks for your work!

**Comment by nillis** [comment]
The issue with the typings is tackled now, but no errors are emit when typecheck is set to strict and call bundle-sfx.

**Comment by nillis** [comment]
#84
