### ISSUE TITLE
React example with hot reload

### ISSUE THREAD

**Issue by jonaskello** [frankwallis/plugin-typescript#87]
I'm currently using typescript+webpack+ts-loader+react but want to move to using jspm, so the react example in this repo seems like the exact setup I want :-). However I cannot get it to work :-(. I run these steps:

```
> git clone https://github.com/frankwallis/plugin-typescript.git
> cd plugin-typescript
> npm install
> cd example/react
> jspm install
> npm start
```

Then when I run localhost:8080 in Chrome I get the messages in the picture below:

![image](https://cloud.githubusercontent.com/assets/664076/12531002/59c88d66-c1f0-11e5-9f1b-cde4e0f6209b.png)

The application itself works but hot reloading does not work. Am I doing something wrong?

**Comment by frankwallis** [comment]
I have just pushed a fix for that error, but there is still a problem with the hot-reloading by default. The issue is this one: https://github.com/capaj/systemjs-hot-reloader/issues/42. To workaround it you need to change ```extends EventEmitter``` to ```extends EventEmitter.default``` in hot-reloader.js. I will try and see if I can come up with some configuration to solve that at some point, but for now to see the hot reloading you will need to use the workaround I'm afraid.

**Comment by jonaskello** [comment]
Thank you, got it working now :-). 
I saw your fix added typescript as transpiler in config.js. I guess this is because systemjs-hot-reloader itself needs to be transpiled by something (maybe babel would have worked too?). I'm new to systemjs/jspm but I'm thinking that if hot-reloader was pre-transpiled when installed then maybe this would not be necessary. But maybe that is not the systemjs/jspm way of doing things?

**Comment by jonaskello** [comment]
I found pre-compilation was already suggested [here](https://github.com/capaj/systemjs-hot-reloader/issues/35#issuecomment-167461642). Closing this as my case works now, thanks again!

**Comment by frankwallis** [comment]
Thanks for the update. In the upcoming version of jspm it will be possible to specify this plugin to be the default transpiler and so this issue should go away then anyway.

**Comment by frankwallis** [comment]
I've added overrides to the examples which fix the ```extends EventEmitter.default``` issue.

**Comment by jonaskello** [comment]
Nice! I tried it from scratch and can verify that the react example now works without any issues.
