### ISSUE TITLE
When running jspm bundle-sfx no ts errors are emit

### ISSUE THREAD

**Issue by nillis** [frankwallis/plugin-typescript#93]
When I create a bundle-sfx with JSPM, no TS errors are emit.

**Comment by nillis** [comment]
#84

**Comment by nillis** [comment]
#84 Also mentioned here

**Comment by frankwallis** [comment]
I'm not able to recreate this - can you provide a repro in the ignore typings project?

**Comment by nillis** [comment]
Yes I'll provide a sample after the weekend

**Comment by frankwallis** [comment]
Likewise, please provide a repro if this is still an issue, thanks.

**Comment by nillis** [comment]
Solved and discussed in https://github.com/nillis/ignore-typings/pull/1
