### ISSUE TITLE
TypeScript 1.8.0 causes compile errors

### ISSUE THREAD

**Issue by nillis** [frankwallis/plugin-typescript#94]
Yesterday 1.8.0 Beta released. I suggest to change the version of typescript in the pacakges.json to 1.7.5 as the Beta causes compile errors, contains debugger statements, ...

**Comment by frankwallis** [comment]
I've locked it in 2.5.6, will take a look  at the errors when I get a chance.

**Comment by meriturva** [comment]
any news? so thanks!

**Comment by frankwallis** [comment]
I've raised this issue: https://github.com/Microsoft/TypeScript/issues/6766
Unfortunately this means you can't use 1.8.0 right now, the issue affexts plugin-typescript and the built in transpiler.

**Comment by vladima** [comment]
@frankwallis PR with the fix in submitted so hopefully it will available in today nightly build

**Comment by frankwallis** [comment]
@vladima, that's great news, thanks

**Comment by frankwallis** [comment]
plugin-typescript@3.0.0 now uses typescript@1.9.0-dev.20160206 where this issue is fixed. 

When typescript@1.8.2 is released I may revert to using that.
